SELECT 1 AS Kolejnosc, 'ZaE_GIDTyp' AS CDN_Pole, 'GID elementu zamowienia - typ (staly 960=Zamowienie)' AS Opis_w_dokumentacji, '960' AS Przykladowe_wartosci, '-' AS Alias_w_widoku, '-' AS Transformacja, 'Nie' AS Uwzglednic, 'COUNT DISTINCT=1 (staly 960)' AS Uzasadnienie, '' AS Komentarz_Analityka
UNION ALL SELECT 2, 'ZaE_GIDFirma', 'GID firmy', '1464833', '-', '-', 'Nie', 'COUNT DISTINCT=1', ''
UNION ALL SELECT 3, 'ZaE_GIDNumer', 'Numer zamowienia (FK ZamNag)', '35,100,200', 'ID_Zamowienia', '=', 'Tak', 'FK do CDN.ZamNag.ZaN_GIDNumer', ''
UNION ALL SELECT 4, 'ZaE_GIDLp', 'Numer kolejny pozycji (czesc PK)', '1,2,3', 'Nr_Pozycji', '=', 'Tak', 'Techniczna czesc klucza PK', ''
UNION ALL SELECT 5, 'ZaE_Pozycja', 'Pozycja wyswietlana na dokumencie', '1,2,3,...', 'Pozycja_Na_Dokumencie', '=', 'Tak', 'COUNT DISTINCT=257 — analogicznie do TraElem (GIDLp moze miec dziury)', ''
UNION ALL SELECT 6, 'JOIN CDN.ZamNag: Numer_Dokumentu', 'Numer zamowienia', 'ZS-2/05/23/PH_4', 'Numer_Dokumentu', 'INNER JOIN ZamNag; SKROT-Numer/MM/YY/Seria — CASE ZaN_ZamTyp: 640=OFZ, 768=OFS, 1152=ZZ, 1280=ZS, ELSE ZAM', 'Tak', 'INNER JOIN zweryfikowany: COUNT(total=275635) = COUNT(z_join=275635) — 0 sierot', ''
UNION ALL SELECT 7, 'JOIN CDN.ZamNag: ZaN_ZamTyp', 'Typ zamowienia', '640,768,1152,1280', 'Typ_Zamowienia', 'JOIN ZamNag; CASE: 640=Oferta zakupu, 768=Oferta sprzedazy, 1152=Zamowienie zakupu, 1280=Zamowienie sprzedazy, 2688=Zapytanie ofertowe zakupu, 2816=Zapytanie ofertowe sprzedazy, ELSE Nieznane(val)', 'Tak', 'Typ dokumentu zamowienia', ''
UNION ALL SELECT 8, 'JOIN CDN.ZamNag: ZaN_Stan', 'Stan zamowienia', '1,2,3,4,5,21', 'Stan_Zamowienia', 'JOIN ZamNag; CASE: 1=Oferta, 2=Zamowienie, 3=Potwierdzone, 4=Zaakceptowane, 5=W realizacji, 19=Odrzucone, 21=Zrealizowane, 35=Anulowane (potw.), 51=Anulowane (arch.+potw.), 53=Zamkniete w realizacji, ELSE Nieznane(val)', 'Tak', 'Stan realizacji zamowienia', ''
UNION ALL SELECT 9, 'JOIN CDN.ZamNag: ZaN_DataWystawienia', 'Data wystawienia zamowienia', '2023-05-15', 'Data_Wystawienia', 'JOIN ZamNag; Clarion DATE: DATEADD(d, ZaN_DataWystawienia, ''18001228'')', 'Tak', 'Core pole analityczne — data dokumentu', ''
UNION ALL SELECT 10, 'ZaE_TwrTyp', 'GID towaru - typ (staly 16)', '16', '-', '-', 'Nie', 'COUNT DISTINCT=1 (staly 16)', ''
UNION ALL SELECT 11, 'ZaE_TwrFirma', 'GID towaru - firma', '1464833', '-', '-', 'Nie', 'COUNT DISTINCT=1', ''
UNION ALL SELECT 12, 'ZaE_TwrNumer', 'Numer towaru (FK TwrKarty)', '2544,3282', 'ID_Towaru', 'CASE WHEN 0 THEN NULL ELSE ZaE_TwrNumer END', 'Tak', 'FK do CDN.TwrKarty', ''
UNION ALL SELECT 13, 'ZaE_TwrLp', 'GID towaru - Lp', '0', '-', '-', 'Nie', 'Skladnik GID (Lp)', ''
UNION ALL SELECT 14, 'ZaE_TwrNazwa', 'Nazwa towaru (przepisana na pozycje)', 'Kos Zapalarka Antenka', 'Nazwa_Towaru', 'RTRIM', 'Tak', 'Nazwa w chwili zamowienia', ''
UNION ALL SELECT 15, 'ZaE_TwrKod', 'Kod towaru', 'KOST0009', 'Kod_Towaru', 'RTRIM', 'Tak', 'Kod w chwili zamowienia', ''
UNION ALL SELECT 16, 'ZaE_KntTyp', 'GID kontrahenta pozycji - typ', '32,0', '-', '-', 'Nie', 'Skladnik GID (typ)', ''
UNION ALL SELECT 17, 'ZaE_KntFirma', 'GID kontrahenta pozycji - firma', '1464833,0', '-', '-', 'Nie', 'Skladnik GID', ''
UNION ALL SELECT 18, 'ZaE_KntNumer', 'Numer kontrahenta na pozycji', '155,0', 'ID_Kontrahenta_Pozycji', 'CASE WHEN 0 THEN NULL ELSE ZaE_KntNumer END', 'Tak', 'FK do CDN.KntKarty; moze roznic sie od kontrahenta w naglowku', ''
UNION ALL SELECT 18.5, 'JOIN CDN.KntKarty: Knt_Akronim', 'Akronim kontrahenta pozycji', 'KOWALSKI', 'Akronim_Kontrahenta_Pozycji', 'LEFT JOIN KntKarty ON Knt_GIDNumer=ZaE_KntNumer AND ZaE_KntNumer>0', 'Tak', 'Dane opisowe FK', ''
UNION ALL SELECT 18.7, 'JOIN CDN.KntKarty: Knt_Nazwa1', 'Nazwa kontrahenta pozycji', 'JAN KOWALSKI SP. Z O.O.', 'Nazwa_Kontrahenta_Pozycji', 'LEFT JOIN KntKarty (ten sam alias) - Knt_Nazwa1', 'Tak', 'Para do Akronim_Kontrahenta_Pozycji', ''
UNION ALL SELECT 19, 'ZaE_KntLp', 'GID kontrahenta - Lp', '0', '-', '-', 'Nie', 'Skladnik GID (Lp)', ''
UNION ALL SELECT 20, 'ZaE_AkwTyp', 'GID akwizytora - typ (32=KntKarty, 8224=KSl, 0=brak)', '32,0,8224', '-', '-', 'Nie', 'Skladnik GID — 8224=Slownik kadr i plac (brak tabeli CDN.KSl*)', ''
UNION ALL SELECT 21, 'ZaE_AkwFirma', 'GID akwizytora - firma', '1464833,0', '-', '-', 'Nie', 'Skladnik GID', ''
UNION ALL SELECT 22, 'ZaE_AkwNumer', 'Numer akwizytora', '538976288,0', 'ID_Akwizytora', 'CASE WHEN ZaE_AkwNumer=0 OR ZaE_AkwTyp!=32 THEN NULL ELSE ZaE_AkwNumer END', 'Tak', 'FK do CDN.KntKarty (tylko AkwTyp=32); typ 8224 brak tabeli — 793 pozycji (0.3%)', ''
UNION ALL SELECT 23, 'JOIN CDN.KntKarty: Akwizytor_Akronim', 'Akronim akwizytora', 'JAN.NOWAK', 'Akwizytor_Akronim', 'LEFT JOIN KntKarty ON AkwNumer i AkwTyp=32; NULL dla typ 8224', 'Tak', 'Dane opisowe FK — tylko AkwTyp=32 (99.7% pozycji)', ''
UNION ALL SELECT 24, 'ZaE_AkwLp', 'GID akwizytora - Lp', '0,1', '-', '-', 'Nie', 'Skladnik GID (Lp)', ''
UNION ALL SELECT 25, 'ZaE_CChTyp', 'GID klasy cechy - typ', '0,208', '-', '-', 'Nie', 'Techniczny GID klasy cechy — 2 distinct', ''
UNION ALL SELECT 26, 'ZaE_CChFirma', 'GID klasy cechy - firma', '0,1464833', '-', '-', 'Nie', 'Skladnik GID', ''
UNION ALL SELECT 27, 'ZaE_CChNumer', 'GID klasy cechy', '0,1', '-', '-', 'Nie', 'Techniczny FK klasy cechy (2 distinct — prawie constant)', ''
UNION ALL SELECT 28, 'ZaE_CChLp', 'GID klasy cechy - Lp', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1', ''
UNION ALL SELECT 29, 'ZaE_MagTyp', 'GID magazynu - typ', '208,0', '-', '-', 'Nie', 'Skladnik GID (typ)', ''
UNION ALL SELECT 30, 'ZaE_MagFirma', 'GID magazynu - firma', '1464833,0', '-', '-', 'Nie', 'Skladnik GID', ''
UNION ALL SELECT 31, 'ZaE_MagNumer', 'Numer magazynu (FK Magazyny)', '1,5,21,8,4', 'ID_Magazynu', '=', 'Tak', 'FK do CDN.Magazyny.MAG_GIDNumer', ''
UNION ALL SELECT 31.5, 'JOIN CDN.Magazyny: MAG_Kod', 'Kod magazynu', 'BUSZ_GL', 'Kod_Magazynu', 'LEFT JOIN Magazyny ON MAG_GIDNumer=ZaE_MagNumer AND MAG_GIDTyp=208', 'Tak', 'Dane opisowe FK — skrot magazynu', ''
UNION ALL SELECT 31.7, 'JOIN CDN.Magazyny: MAG_Nazwa', 'Nazwa magazynu', 'Magazyn glowny Buszewo', 'Nazwa_Magazynu', 'LEFT JOIN Magazyny (ten sam alias)', 'Tak', 'Dane opisowe FK — pelna nazwa magazynu', ''
UNION ALL SELECT 32, 'ZaE_MagLp', 'GID magazynu - Lp', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1', ''
UNION ALL SELECT 33, 'ZaE_TStamp', 'Fizyczny czas utworzenia pozycji (Clarion TS)', '1054402940', 'DataCzas_Utworzenia', 'Clarion TIMESTAMP: CASE WHEN =0 THEN NULL ELSE DATEADD(ss, ZaE_TStamp, ''1990-01-01'') END', 'Tak', 'Fizyczny czas zapisu — rozni sie od daty dokumentu', ''
UNION ALL SELECT 34, 'ZaE_Ilosc', 'Ilosc towaru', '25.0000', 'Ilosc', '=', 'Tak', 'Core pole analityczne', ''
UNION ALL SELECT 35, 'ZaE_JmZ', 'Symbol JM', 'szt.,opak.,kg', 'Jednostka_Miary', 'RTRIM', 'Tak', 'JM w ktorej realizowane zamowienie', ''
UNION ALL SELECT 36, 'ZaE_TypJm', 'Typ przelicznika JM (1-dziesietny 2-calkowity)', '1,2', '-', '-', 'Nie', 'Techniczny typ przelicznika UI', ''
UNION ALL SELECT 37, 'ZaE_JmFormat', 'Miejsca po przecinku JM podstawowej', '0,1,2', '-', '-', 'Nie', 'Formatowanie UI', ''
UNION ALL SELECT 38, 'ZaE_JmFormatZ', 'Miejsca po przecinku JM pomocniczej', '0,1,2', '-', '-', 'Nie', 'Formatowanie UI', ''
UNION ALL SELECT 39, 'ZaE_PrzeliczM', 'Mianownik przelicznika JM', '1', '-', '-', 'Nie', 'COUNT DISTINCT=1 (1)', ''
UNION ALL SELECT 40, 'ZaE_PrzeliczL', 'Licznik przelicznika JM', '1,5,12', 'Przelicznik_JM', '=', 'Tak', 'Przelicznik JM; 1 gdy brak przeliczenia', ''
UNION ALL SELECT 41, 'ZaE_GrupaPod', 'Symbol grupy podatkowej', 'A,B,C', 'Grupa_VAT', '=', 'Tak', '3 distinct wartosci', ''
UNION ALL SELECT 42, 'ZaE_StawkaPod', 'Stawka podatku (%)', '0,8,23', 'Stawka_VAT', '=', 'Tak', '3 distinct wartosci', ''
UNION ALL SELECT 43, 'ZaE_FlagaVAT', 'Flaga VAT', '1', '-', '-', 'Nie', 'COUNT DISTINCT=1 (staly 1=Opodatkowany)', ''
UNION ALL SELECT 44, 'ZaE_Zrodlowa', 'Stawka zrodlowa', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 45, 'ZaE_Waluta', 'Symbol waluty', 'PLN,EUR', 'Waluta', '=', 'Tak', '2 distinct wartosci', ''
UNION ALL SELECT 46, 'ZaE_NrKursu', 'Nr kolumny kursowej NBP', '1', '-', '-', 'Nie', 'COUNT DISTINCT=1 — techniczne', ''
UNION ALL SELECT 47, 'ZaE_Rabat', 'Procent rabatu', '17.00,0.00', 'Rabat_Procent', '=', 'Tak', '1094 distinct wartosci', ''
UNION ALL SELECT 48, 'ZaE_Cecha', 'Cecha towaru na pozycji', '4 distinct', 'Cecha_Towaru', 'NULLIF(RTRIM(ZaE_Cecha), '''')', 'Tak', '4 distinct — analogicznie do TraElem', ''
UNION ALL SELECT 49, 'ZaE_CenaKatalogowa', 'Cena katalogowa towaru', '2.2000', 'Cena_Katalogowa', '=', 'Tak', 'Cena wyjsciowa przed rabatami', ''
UNION ALL SELECT 50, 'ZaE_CenaOferowana', 'Cena oferowana (po rabatach handlowych)', '1.8300', 'Cena_Oferowana', '=', 'Tak', 'Cena po zastosowaniu rabatow handlowych', ''
UNION ALL SELECT 51, 'ZaE_CenaUzgodniona', 'Cena uzgodniona (finalna na pozycji)', '1.8300', 'Cena_Uzgodniona', '=', 'Tak', 'Core pole analityczne — cena realizacji', ''
UNION ALL SELECT 52, 'ZaE_RodzajCenyBazowej', 'Rodzaj ceny bazowej', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 53, 'ZaE_ProgTyp', 'Typ progu upustowego', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 54, 'ZaE_Prog', 'Wartosc progowa', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 55, 'ZaE_UpustTyp', 'Typ upustu progowego', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 56, 'ZaE_Upust', 'Wartosc upustu', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 57, 'ZaE_UpustKntTyp', 'Typ upustu klienta', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 58, 'ZaE_UpustKnt', 'Upust klienta', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 59, 'ZaE_ReETyp', 'GID rezerwacji - typ', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0) — nie wygenerowano rezerwacji', ''
UNION ALL SELECT 60, 'ZaE_ReEFirma', 'GID rezerwacji - firma', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1', ''
UNION ALL SELECT 61, 'ZaE_ReENumer', 'GID rezerwacji - numer', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 62, 'ZaE_ReELp', 'GID rezerwacji - Lp', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 63, 'ZaE_ReEProdLp', 'GID rezerwacji - prod Lp', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 64, 'ZaE_DataWaznosciRez', 'Data waznosci rezerwacji (Clarion DATE)', '81244,93890', 'Data_Waznosci_Rezerwacji', 'Clarion DATE: CASE WHEN val BETWEEN 1 AND 90000 THEN CAST(DATEADD(d, val, ''18001228'') AS DATE) ELSE NULL END (93890=sentinel brak wygasania → NULL)', 'Tak', '99.1% wartosci = 93890 (sentinel no-expiry → NULL); real dates dla 2488 pozycji', ''
UNION ALL SELECT 65, 'ZaE_WartoscPoRabacie', 'Wartosc pozycji po rabacie (waluta)', '45.75', 'Wartosc_Po_Rabacie', '=', 'Tak', 'Core pole analityczne — wartosc realizacji', ''
UNION ALL SELECT 66, 'ZaE_DataPotwDst', 'Data potwierdzenia dostawy (Clarion DATE)', '81238-93890', 'Data_Potwierdzenia_Dostawy', 'Clarion DATE: CASE WHEN val BETWEEN 1 AND 109211 THEN CAST(DATEADD(d, val, ''18001228'') AS DATE) ELSE NULL END', 'Tak', 'Clarion DATE, min=81238, max=93890 — data potwierdzenia realizacji dostawy', ''
UNION ALL SELECT 67, 'ZaE_DataAktywacjiRez', 'Data aktywacji rezerwacji (Clarion DATE)', '81238-82258', 'Data_Aktywacji_Rezerwacji', 'Clarion DATE: CASE WHEN val BETWEEN 1 AND 109211 THEN CAST(DATEADD(d, val, ''18001228'') AS DATE) ELSE NULL END', 'Tak', 'Clarion DATE, min=81238, max=82258', ''
UNION ALL SELECT 68, 'ZaE_DataOdZam', 'Liczba dni od wystawienia do realizacji', '-25,0,5,135', 'Dni_Do_Realizacji', '=', 'Tak', 'Numeric (nie data): opis w dokumentacji — ilosc dni od daty wystawienia do realizacji', ''
UNION ALL SELECT 69, 'ZaE_PrecyzjaCeny', 'Precyzja ceny (miejsca po przecinku)', '2,4', '-', '-', 'Nie', 'Techniczne formatowanie — 2 distinct', ''
UNION ALL SELECT 70, 'ZaE_Rownanie', 'Czy cena * ilosc = wartosc', '0,1', 'Rowna_IloscxCena', 'CASE: 0=Nieaktywne, 1=Aktywne, ELSE Nieznane(val)', 'Tak', 'Analogicznie do TraElem — kontrolna flaga', ''
UNION ALL SELECT 71, 'ZaE_FlagaNB', 'N=od netto B=od brutto', 'N', '-', '-', 'Nie', 'COUNT DISTINCT=1 (zawsze N=od netto)', ''
UNION ALL SELECT 72, 'ZaE_Licencja', 'Numer licencji modulu', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 73, 'ZaE_RabatPromocyjny', 'Rabat z promocji (%)', '0.0000,17.0000', 'Rabat_Promocyjny', '=', 'Tak', '37 distinct wartosci', ''
UNION ALL SELECT 74, 'ZaE_RabatKorekta', 'Rabat korekty', '0.00', 'Rabat_Korekta', '=', 'Tak', '12 distinct wartosci', ''
UNION ALL SELECT 75, 'ZaE_Promocje', 'Bitmask promocji', '0,65891', '-', '-', 'Nie', '16 distinct, bitmask — poza zakresem widoku (analogicznie do TraElem)', ''
UNION ALL SELECT 76, 'ZaE_ZstTyp', 'GID zestawienia - typ', '0,960', '-', '-', 'Nie', 'Niezidentyfikowany FK zestawienia — 6 distinct numer', ''
UNION ALL SELECT 77, 'ZaE_ZstFirma', 'GID zestawienia - firma', '0,1464833', '-', '-', 'Nie', 'Skladnik GID', ''
UNION ALL SELECT 78, 'ZaE_ZstNumer', 'GID zestawienia - numer', '0,6174,6119', '-', '-', 'Nie', 'Niezidentyfikowany FK zestawienia — brak opisu w dokumentacji', ''
UNION ALL SELECT 79, 'ZaE_ZstLp', 'GID zestawienia - Lp', '0,1', '-', '-', 'Nie', 'Skladnik GID', ''
UNION ALL SELECT 80, 'ZaE_PrecyzjaCenyPocz', 'Precyzja ceny poczatkowej', '2,4', '-', '-', 'Nie', 'Techniczne formatowanie', ''
UNION ALL SELECT 81, 'ZaE_CenaSpr', 'ID cennika sprzedazy (FK TwrCenyNag)', '-32000,0,1,2', 'ID_Cennika', 'CASE WHEN ZaE_CenaSpr IN (0, -32000) THEN NULL ELSE ZaE_CenaSpr END', 'Tak', 'FK do CDN.TwrCenyNag; 0 i -32000 = brak cennika; 10 distinct', ''
UNION ALL SELECT 81.5, 'CTE CenBase: TCN_Nazwa', 'Nazwa cennika', 'Detaliczny,Hurtowy', 'Nazwa_Cennika', 'CTE MIN(TCN_Id) per TCN_RodzajCeny — wzorzec z TraElem i TraNag', 'Tak', 'Dane opisowe FK — para do ID_Cennika', ''
UNION ALL SELECT 82, 'ZaE_RodzajDatyRealizacji', 'Rodzaj daty realizacji', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 83, 'ZaE_KGOJednostkowe', 'KGO jednostkowe', '0.00', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0.00)', ''
UNION ALL SELECT 84, 'ZaE_OddElemId', 'Id pozycji z e-Sklepu', '0,19,14,17,23', 'ID_Pozycji_eSklepu', 'CASE WHEN ZaE_OddElemId = 0 THEN NULL ELSE ZaE_OddElemId END', 'Tak', 'Dokumentacja: Id pozycji z e-Sklepu; 0 = brak e-sklepu; distinct 138874 unikalnych ID', ''
UNION ALL SELECT 85, 'ZaE_IloscMin', 'Minimalna ilosc zamowienia', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 86, 'ZaE_IloscMax', 'Maksymalna ilosc zamowienia', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 87, 'ZaE_PakietId', 'ID pakietu', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 88, 'ZaE_Gratis', 'Flaga gratisu', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 89, 'ZaE_PromocjaProgID', 'ID progu promocji', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 90, 'ZaE_Zlom', 'Flaga zlomu', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 91, 'ZaE_FormatkaCyr', 'Formatka cyrylicy', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 92, 'ZaE_KPNId', 'ID KPN', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 93, 'ZaE_TypCenyNabycia', 'Typ ceny nabycia', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 94, 'ZaE_PakietWymaganaPoz', 'Flaga wymaganej pozycji pakietu', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 95, 'ZaE_PakietTwgNumer', 'Numer TwrGrupy pakietu', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 96, 'ZaE_PakietTwgTyp', 'Typ TwrGrupy pakietu', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 97, 'ZaE_RabatOpeGen', 'Rabat operatora globalny', '0.00', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0.00)', ''
UNION ALL SELECT 98, 'ZaE_WymuszonePRMID', 'ID wymuszonej promocji', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 99, 'ZaE_Punkty', 'Punkty lojalnosciowe', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 100, 'ZaE_Nagroda', 'Flaga nagrody', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 101, 'ZaE_ReNNumer', 'Numer reklamacji', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 102, 'ZaE_OplataSpozFlaga', 'Flaga oplaty spozywczej', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 103, 'ZaE_StawkaCukierStala', 'Stawka podatku cukrowego stala', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 104, 'ZaE_StawkaCukierZmienna', 'Stawka podatku cukrowego zmienna', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 105, 'ZaE_StawkaKofeina', 'Stawka podatku kofeinowego', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 106, 'ZaE_JmDzielWZWM', 'Dziel JM w WZ/WM', '0,1', '-', '-', 'Nie', 'Techniczne 2 distinct — formatowanie WZ/WM', ''
UNION ALL SELECT 107, 'ZaE_GUID', 'GUID wiersza', 'uuid', '-', '-', 'Nie', 'Techniczny identyfikator replikacji — id 275421 distinct', ''
ORDER BY Kolejnosc
