SELECT 1 AS Kolejnosc, 'TrE_GIDTyp' AS CDN_Pole, 'GID elementu transakcji - typ dokumentu' AS Opis_w_dokumentacji, '2034,2033,2001,1521,1489' AS Przykladowe_wartosci, 'Typ_Dokumentu' AS Alias_w_widoku, 'CASE - identyczny wzorzec jak AIBI.TraNag' AS Transformacja, 'Tak' AS Uwzglednic, 'Typ dokumentu - analogicznie do AIBI.TraNag' AS Uzasadnienie, '' AS Komentarz_Analityka
UNION ALL SELECT 2, 'TrE_GIDFirma', 'GID elementu transakcji', '1464833', '-', '-', 'Nie', 'COUNT DISTINCT=1', ''
UNION ALL SELECT 3, 'TrE_GIDNumer', 'Unikalny numer naglowka transakcji (FK TraNag)', '481345,61,64', 'ID_Dokumentu', '=', 'Tak', 'FK do CDN.TraNag.TrN_GIDNumer', ''
UNION ALL SELECT 4, 'TrE_GIDLp', 'Numer kolejny elementu transakcji (czesc PK)', '1,2,3,9,10', 'Nr_Pozycji', '=', 'Tak', 'Techniczna czesc klucza PK; nie ulega przenumerowaniu', ''
UNION ALL SELECT 5, 'TrE_Pozycja', 'Pozycja wyswietlana na dokumencie', '1,2,3,...', 'Pozycja_Na_Dokumencie', '=', 'Tak', 'COUNT DISTINCT roznic (GIDLp vs Pozycja)=156 — nie jest redundantna; Pozycja jest ciagla (bez dzur), GIDLp moze miec dziury po usunieciu', ''
UNION ALL SELECT 6, 'JOIN CDN.TraNag: TrN', 'Numer dokumentu z TraNag', 'FS-1/01/24/SPKR', 'Numer_Dokumentu', 'LEFT JOIN TraNag; formula taka jak AIBI.TraNag', 'Tak', 'Core pole analityczne - bez numeru widok niezdatny do uzycia', ''
UNION ALL SELECT 7, 'JOIN CDN.TraNag: TrN_Data2', 'Data wystawienia dokumentu', '2024-01-15', 'Data_Wystawienia', 'LEFT JOIN TraNag; Clarion DATE z TrN_Data2', 'Tak', 'Core pole analityczne - obroty per okres', ''
UNION ALL SELECT 8, 'TrE_TwrTyp', 'GID towaru - staly typ 16', '16', '-', '-', 'Nie', 'COUNT DISTINCT=1 (staly 16)', ''
UNION ALL SELECT 9, 'TrE_TwrFirma', 'GID towaru', '1464833', '-', '-', 'Nie', 'COUNT DISTINCT=1', ''
UNION ALL SELECT 10, 'TrE_TwrNumer', 'Numer towaru z CDN.TwrKarty', '3282,3271,6420,0', 'ID_Towaru', 'CASE WHEN 0 THEN NULL ELSE TrE_TwrNumer END', 'Tak', 'FK do CDN.TwrKarty; 0 dla pozycji A-Vista', ''
UNION ALL SELECT 11, 'TrE_TwrLp', 'GID towaru - Lp', '-', '-', '-', 'Nie', 'Skladnik GID (Lp)', ''
UNION ALL SELECT 12, 'TrE_TwrNazwa', 'Nazwa towaru (przepisana z karty, podlega edycji)', 'Wk CEiM zniczowy 4', 'Nazwa_Towaru', 'RTRIM', 'Tak', 'Nazwa w chwili transakcji (moze roznic sie od aktualnej)', ''
UNION ALL SELECT 13, 'TrE_TwrKod', 'Kod towaru', 'CWKZ0033,A-VISTA', 'Kod_Towaru', 'RTRIM', 'Tak', 'Kod w chwili transakcji', ''
UNION ALL SELECT 14, 'TrE_TypTwr', 'Typ towaru (przepisany z Twr_Typ)', '1,2,3,4,6', 'Typ_Towaru', 'CASE: 1=Towar, 2=Produkt, 3=Koszt, 4=Usluga, 6=A-Vista, ELSE Nieznane(val)', 'Tak', 'Typ elementu; 6=A-Vista - pozycja bez stalej karty towaru', ''
UNION ALL SELECT 15, 'TrE_KntTyp', 'GID kontrahenta - typ', '32,0', '-', '-', 'Nie', 'Skladnik GID (typ)', ''
UNION ALL SELECT 16, 'TrE_KntFirma', 'GID kontrahenta - firma', '1464833,0', '-', '-', 'Nie', 'Skladnik GID', ''
UNION ALL SELECT 17, 'TrE_KntNumer', 'Numer kontrahenta na pozycji', '2430,2147,0', 'ID_Kontrahenta_Pozycji', 'CASE WHEN 0 THEN NULL ELSE TrE_KntNumer END', 'Tak', 'FK do CDN.KntKarty; moze roznic sie od kontrahenta w naglowku', ''
UNION ALL SELECT 18, 'JOIN CDN.KntKarty: Knt_Akronim', 'Akronim kontrahenta', 'KOWALSKI', 'Akronim_Kontrahenta_Pozycji', 'LEFT JOIN KntKarty ON Knt_GIDNumer=TrE_KntNumer AND TrE_KntNumer>0', 'Tak', 'Dane opisowe FK - wymagane dla kazdego ID', ''
UNION ALL SELECT 18.5, 'JOIN CDN.KntKarty: Knt_Nazwa1', 'Nazwa kontrahenta', 'JAN KOWALSKI SP. Z O.O.', 'Nazwa_Kontrahenta_Pozycji', 'LEFT JOIN KntKarty (ten sam alias knt_pos) - Knt_Nazwa1', 'Tak', 'Dane opisowe FK - para do Akronim_Kontrahenta_Pozycji', ''
UNION ALL SELECT 19, 'TrE_KntLp', 'GID kontrahenta - Lp', '0', '-', '-', 'Nie', 'Skladnik GID (Lp)', ''
UNION ALL SELECT 20, 'TrE_AkwTyp', 'GID akwizytora - typ (32=KntKarty 944=PrcKarty)', '0,32,944', '-', '-', 'Nie', 'Skladnik GID - wartosci techniczne', ''
UNION ALL SELECT 21, 'TrE_AkwFirma', 'GID akwizytora - firma', '1464833,0', '-', '-', 'Nie', 'Skladnik GID', ''
UNION ALL SELECT 22, 'TrE_AkwNumer', 'Numer akwizytora (KntKarty lub PrcKarty)', '5,10,13,0', 'ID_Akwizytora', 'CASE WHEN 0 THEN NULL ELSE TrE_AkwNumer END', 'Tak', 'FK do KntKarty(AkwTyp=32) lub PrcKarty(AkwTyp=944)', ''
UNION ALL SELECT 23, 'JOIN Akw Knt/Prc: Akronim', 'Akronim akwizytora', 'JAN.NOWAK', 'Akwizytor_Akronim', 'COALESCE(knt.Knt_Akronim, prc.Prc_Akronim) - wzorzec z TraNag', 'Tak', 'Dane opisowe FK - wymagane dla kazdego ID', ''
UNION ALL SELECT 24, 'TrE_AkwLp', 'GID akwizytora - Lp', '0', '-', '-', 'Nie', 'Skladnik GID (Lp)', ''
UNION ALL SELECT 25, 'TrE_TrnTStamp', 'Fizyczny czas utworzenia transakcji (Clarion TS)', '~10^9', 'DataCzas_Utworzenia', 'Clarion TIMESTAMP - DATEADD(ss,col,1990-01-01)', 'Tak', 'Fizyczny czas zapisu - rozni sie od daty dokumentu', ''
UNION ALL SELECT 26, 'TrE_Punkty', 'Ilosc punktow na pozycji', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 27, 'TrE_Ilosc', 'Ilosc towaru w JM podstawowych', '1,2,3,5,12', 'Ilosc', '=', 'Tak', 'Core pole analityczne', ''
UNION ALL SELECT 28, 'TrE_JmFormat', 'Miejsca po przecinku przy edycji ilosci', '0,1,2,4', '-', '-', 'Nie', 'Formatowanie UI - nie dane', ''
UNION ALL SELECT 29, 'TrE_JmZ', 'Symbol JM realizacji transakcji', 'szt.,opak.,kg,paleta', 'Jednostka_Miary', 'RTRIM', 'Tak', 'JM w ktorej realizowana transakcja', ''
UNION ALL SELECT 30, 'TrE_JmFormatZ', 'Miejsca po przecinku JM pomocniczej', '0,1,2,4', '-', '-', 'Nie', 'Formatowanie UI', ''
UNION ALL SELECT 31, 'TrE_TypJm', 'Typ przelicznika (1-dziesietny 2-calkowity)', '1,2', '-', '-', 'Nie', 'Techniczny typ przelicznika', ''
UNION ALL SELECT 32, 'TrE_PrzeliczM', 'Mianownik przelicznika', '1', '-', '-', 'Nie', 'COUNT DISTINCT=1 (1)', ''
UNION ALL SELECT 33, 'TrE_PrzeliczL', 'Licznik przelicznika JM', '1,5,12,6,25', 'Przelicznik_JM', '=', 'Tak', 'Przelicznik z JM podstawowych; 1 gdy transakcja w JM podst.', ''
UNION ALL SELECT 34, 'TrE_GrupaPod', 'Symbol grupy podatkowej', 'A,B,C,D,E,F,G', 'Grupa_VAT', '=', 'Tak', '', ''
UNION ALL SELECT 35, 'TrE_StawkaPod', 'Stawka podatku (%)', '0,5,7,8,23', 'Stawka_VAT', '=', 'Tak', '', ''
UNION ALL SELECT 36, 'TrE_FlagaVat', 'Rozroznienie stawki zero', '0,1,2', 'Flaga_VAT', 'CASE: 0=Zwolniony, 1=Opodatkowany, 2=Nie podlega, ELSE Nieznane(val)', 'Tak', '', ''
UNION ALL SELECT 37, 'TrE_Zrodlowa', 'Stawka poczatkowa gdy znizona', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 38, 'TrE_Akcyza', 'Stawka akcyzowa (%)', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 39, 'TrE_Waluta', 'Symbol waluty', 'PLN,EUR,USD', 'Waluta', '=', 'Tak', '', ''
UNION ALL SELECT 40, 'TrE_NrKursu', 'Numer kolumny kursowej', '0,1', '-', '-', 'Nie', 'Techniczny nr kolumny kursowej NBP', ''
UNION ALL SELECT 41, 'TrE_KursM', 'Mianownik kursu (1 lub 100)', '1,100', 'Kurs_Mianownik', '=', 'Tak', 'Potrzebny do wyliczenia kursu: Kurs=KursL/KursM', ''
UNION ALL SELECT 42, 'TrE_KursL', 'Licznik kursu', '1.00,426.78,429.81', 'Kurs_Licznik', '=', 'Tak', 'Kurs w PLN per KursM jednostek waluty', ''
UNION ALL SELECT 43, 'TrE_Poczatkowa', 'Cena poczatkowa w walucie transakcji', '5.50,1.00,0.00', 'Cena_Poczatkowa_Waluta', '=', 'Tak', 'Jedyne pole ceny w TraElem (reszta to wartosci)', ''
UNION ALL SELECT 44, 'TrE_FlagaNB', 'N=od netto B=od brutto (kalkulacja)', 'N,B', 'Kalkulacja_VAT', 'CASE: N=Od netto, B=Od brutto, ELSE Nieznane(val)', 'Tak', 'Sposob kalkulacji VAT na pozycji', ''
UNION ALL SELECT 45, 'TrE_Rabat', 'Procent rabatu', '0,10,15,20,22', 'Rabat_Procent', '=', 'Tak', '', ''
UNION ALL SELECT 46, 'TrE_WartoscPoRabacie', 'Wartosc po rabacie (waluta transakcji)', '10.00,24.75,0.00', 'Wartosc_Po_Rabacie_Waluta', '=', 'Tak', '', ''
UNION ALL SELECT 47, 'TrE_KsiegowaNetto', 'Wartosc ksiegowa netto (PLN)', '9.76,24.75,0.00', 'Wartosc_Netto_PLN', '=', 'Tak', 'Core pole analityczne: obrot netto', ''
UNION ALL SELECT 48, 'TrE_KsiegowaBrutto', 'Wartosc ksiegowa brutto (PLN)', '10.00,30.44,0.00', 'Wartosc_Brutto_PLN', '=', 'Tak', '', ''
UNION ALL SELECT 49, 'TrE_RzeczywistaNetto', 'Wartosc rzeczywista netto', '9.76,3.25,0.00', 'Wartosc_Rzeczywista_Netto_PLN', '=', 'Tak', '', ''
UNION ALL SELECT 50, 'TrE_KosztKsiegowy', 'Wartosc ksiegowa kosztu', '38.64,0.04,0.00', 'Koszt_Ksiegowy_PLN', '=', 'Tak', 'Koszt wlasny sprzedazy lub KsiegowaNetto dla przychodow', ''
UNION ALL SELECT 51, 'TrE_KosztRzeczywisty', 'Wartosc rzeczywista kosztu', '40.38,30.00,0.00', 'Koszt_Rzeczywisty_PLN', '=', 'Tak', 'Rozni sie od ksiegowego przy imporcie z clem', ''
UNION ALL SELECT 52, 'TrE_ProgTyp', 'Typ progu upustowego', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 53, 'TrE_Prog', 'Wartosc progowa', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 54, 'TrE_UpustTyp', 'Typ upustu progowego', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 55, 'TrE_Upust', 'Wartosc upustu progowego', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 56, 'TrE_UpustKnt', 'Upust dla kontrahenta na towar', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0.0000)', ''
UNION ALL SELECT 57, 'TrE_UpustKntTyp', 'Typ upustu dla kontrahenta', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 58, 'TrE_IloscDPPrzed', 'Ilosc przed deprecjacja', '0,16,40', '-', '-', 'Nie', 'Dane ksiegowe deprecjacji - poza zakresem widoku', ''
UNION ALL SELECT 59, 'TrE_KsiegowyDPPrzed', 'Koszt ksiegowy przed deprecjacja', '0', '-', '-', 'Nie', 'Deprecjacja - poza zakresem widoku', ''
UNION ALL SELECT 60, 'TrE_ZlcTyp', 'GID pozycji zlecenia - typ', '0,960,1489', '-', '-', 'Nie', 'FK zlecenia; TrE_ZlcNumer ma tylko 6 distinct wartosci - praktycznie puste', ''
UNION ALL SELECT 61, 'TrE_ZlcFirma', 'GID pozycji zlecenia - firma', '0,1464833', '-', '-', 'Nie', 'Skladnik GID', ''
UNION ALL SELECT 62, 'TrE_ZlcNumer', 'GID pozycji zlecenia - numer', '0,1611,1625,3642', '-', '-', 'Nie', 'COUNT DISTINCT=6 - rzadko uzywane', ''
UNION ALL SELECT 63, 'TrE_ZlcLp', 'GID pozycji zlecenia - Lp', '0..12', '-', '-', 'Nie', 'Skladnik GID', ''
UNION ALL SELECT 64, 'TrE_RecTyp', 'Identyfikator receptury - typ', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 65, 'TrE_RecFirma', 'Identyfikator receptury - firma', '0,1464833', '-', '-', 'Nie', 'Skladnik GID', ''
UNION ALL SELECT 66, 'TrE_RecNumer', 'Identyfikator receptury - numer', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 67, 'TrE_RecLp', 'Identyfikator receptury - Lp', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 68, 'TrE_Cena', 'Cena jednostkowa pozycji', '1.00,4.99,5.00,8.00', 'Cena_Jednostkowa', '=', 'Tak', '', ''
UNION ALL SELECT 69, 'TrE_Rownanie', 'Ilosc x cena = wartosc (flag)', '0,1', 'Rowna_IloscxCena', 'CASE: 0=Nieaktywne, 1=Aktywne, ELSE Nieznane(val)', 'Tak', 'Czy na pozycji obowiazuje rownanie ilosc*cena=wartosc', ''
UNION ALL SELECT 70, 'TrE_OdKsiegowych', 'Wartosci walutowe od ksiegowych', '0,1', 'Wartosci_Od_Ksiegowych', 'CASE: 0=Nie, 1=Tak, ELSE Nieznane(val)', 'Tak', 'Czy wartosci walutowe sa liczone od wartosci ksiegowych', ''
UNION ALL SELECT 71, 'TrE_RzeczywistyDPPrzed', 'Koszt rzeczywisty przed deprecjacja', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 72, 'TrE_PCN', 'Kod taryfy celnej', 'pusty string', '-', '-', 'Nie', 'COUNT DISTINCT=1 (pusty string)', ''
UNION ALL SELECT 73, 'TrE_PrecyzjaCeny', 'Precyzja ceny', '0,2,4', '-', '-', 'Nie', 'Formatowanie UI', ''
UNION ALL SELECT 74, 'TrE_VatTyp', 'GID rekordu VAT - typ dokumentu', '2034,1603...', '-', '-', 'Nie', 'Zlozony FK do systemu VAT - poza zakresem widoku', ''
UNION ALL SELECT 75, 'TrE_VatFirma', 'GID rekordu VAT - firma', '0,1464833', '-', '-', 'Nie', 'Skladnik GID', ''
UNION ALL SELECT 76, 'TrE_VatNumer', 'GID rekordu VAT - numer', '0,481133...', '-', '-', 'Nie', 'Zlozony FK do systemu VAT - poza zakresem', ''
UNION ALL SELECT 77, 'TrE_VatLp', 'GID rekordu VAT - Lp', '0,1,2,3', '-', '-', 'Nie', 'Skladnik GID', ''
UNION ALL SELECT 78, 'TrE_KosztVat', 'Techniczny flag kosztu VAT', '0,1', '-', '-', 'Nie', 'Techniczny flag', ''
UNION ALL SELECT 79, 'TrE_KosztNetto', 'Techniczny flag kosztu netto', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 80, 'TrE_Licencja', 'Licencja', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 81, 'TrE_KrajPoch', 'Kraj pochodzenia', 'PL,DE,NL,IE,SI,pusty', 'Kraj_Pochodzenia', 'NULLIF(RTRIM, pusty string) -> NULL gdy puste', 'Tak', 'Przydatne dla analizy importu; 9 distinct', ''
UNION ALL SELECT 82, 'TrE_RabatPromocyjny', 'Rabat promocyjny (%)', '0,10,15,20', 'Rabat_Promocyjny', '=', 'Tak', 'Rabat wynikajacy z promocji', ''
UNION ALL SELECT 83, 'TrE_RabatKorekta', 'Korekta rabatu (%)', '0,-3,-10,-20', 'Rabat_Korekta', '=', 'Tak', 'Korekta rabatu - moze byc ujemna dla rabatu zbiorczego', ''
UNION ALL SELECT 84, 'TrE_Promocje', 'Bitmask aktywnych promocji', '0,65891,196641', '-', '-', 'Nie', 'Bitmask - zlozona interpretacja, poza zakresem widoku', ''
UNION ALL SELECT 85, 'TrE_ZstTyp', 'GID towaru zastepczego - typ', '0,16', '-', '-', 'Nie', 'FK towaru zastepczego - poza zakresem widoku', ''
UNION ALL SELECT 86, 'TrE_ZstFirma', 'GID towaru zastepczego - firma', '0,1464833', '-', '-', 'Nie', 'Skladnik GID', ''
UNION ALL SELECT 87, 'TrE_ZstNumer', 'GID towaru zastepczego - numer', '0,5780,6174...', '-', '-', 'Nie', 'Towar zastepczy - poza zakresem widoku', ''
UNION ALL SELECT 88, 'TrE_ZstLp', 'GID towaru zastepczego - Lp', '0,1,2', '-', '-', 'Nie', 'Skladnik GID', ''
UNION ALL SELECT 89, 'TrE_PrecyzjaCenyPocz', 'Precyzja ceny poczatkowej', '0,2,4', '-', '-', 'Nie', 'Formatowanie UI', ''
UNION ALL SELECT 90, 'TrE_ZwroconoCalaIlosc', 'Zwrocono calosc', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 91, 'TrE_RodzajCenyBazowej', 'Identyfikator ceny bazowej', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 92, 'TrE_KosztBazowy', 'Cena bazowa', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 93, 'TrE_WartoscBazowa', 'Wartosc w cenie bazowej', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 94, 'TrE_CenaSpr', 'Numer ceny domyslnej dla transakcji', '-32000,0,1..9', 'ID_Cennika', 'CASE: 0 lub -32000 -> NULL, inaczej TrE_CenaSpr', 'Tak', 'Identyfikuje uzyty cennik; -32000=nieokreslony; 0=brak', ''
UNION ALL SELECT 94.5, 'JOIN CDN.TwrCenyNag: TCN_Nazwa', 'Nazwa cennika', 'CMENTARZ,BRICO', 'Nazwa_Cennika', 'CTE CenBase MIN(TCN_Id) per TCN_RodzajCeny - identyczny wzorzec jak TraNag; RTRIM', 'Tak', 'Dane opisowe FK do cennika - para do ID_Cennika', ''
UNION ALL SELECT 95, 'TrE_CenaPoRabacie', 'Cena jednostkowa po rabacie', '8.00,6.00,0.00', 'Cena_Po_Rabacie', '=', 'Tak', '', ''
UNION ALL SELECT 96, 'TrE_CChTyp', 'Typ cechy towaru', '0,192', '-', '-', 'Nie', 'Techniczne ID klasy cechy - zbedne gdy eksponujemy wartosc', ''
UNION ALL SELECT 97, 'TrE_CChNumer', 'Klasa cechy towaru', '0,1', '-', '-', 'Nie', 'Techniczne ID klasy cechy', ''
UNION ALL SELECT 98, 'TrE_Cecha', 'Wartosc cechy towaru (partia/seria)', '138.P4/2J,115.1J', 'Cecha_Towaru', 'NULLIF(RTRIM, pusty string) -> NULL gdy puste', 'Tak', 'Numer partii lub serii; 32 distinct wartosci', ''
UNION ALL SELECT 99, 'TrE_KGOJednostkowe', 'KGO jednostkowe', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 100, 'TrE_IloscMin', 'Min zakres ilosci', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 101, 'TrE_IloscMax', 'Max zakres ilosci', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 102, 'TrE_PakietId', 'Identyfikator promocji pakietowej', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 103, 'TrE_Gratis', 'Rodzaj elementu pakietowego (0=elem 1=gratis)', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 104, 'TrE_PromocjaProgID', 'ID progu promocji', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 105, 'TrE_FormatkaCyr', 'Dane wprowadzane cyrylica', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 106, 'TrE_Zlom', 'Element traktowany jako zlom (0=elem 1=zlom)', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 107, 'TrE_IloscPrzedKorekta', 'Ilosc towaru oryginalu', '0,1,2,3,5', 'Ilosc_Przed_Korekta', '=', 'Tak', 'Dla dokumentow korygujacych (FSK/PAK/FZK); 0 na zwyklych', ''
UNION ALL SELECT 108, 'TrE_CenaPrzedKorekta', 'Cena jednostkowa oryginalu', '0,12.99,42.50', 'Cena_Przed_Korekta', '=', 'Tak', '', ''
UNION ALL SELECT 109, 'TrE_WartoscPrzedKorekta', 'Wartosc przed korekta (PLN)', '0,4.86,16.49', 'Wartosc_Przed_Korekta_PLN', '=', 'Tak', '', ''
UNION ALL SELECT 110, 'TrE_GrupaPodPrzedKorekta', 'Grupa VAT oryginalu', 'A,D,G,pusty', 'Grupa_VAT_Przed_Korekta', 'NULLIF(RTRIM, pusty string) -> NULL gdy puste', 'Tak', 'NULL gdy nie korekta', ''
UNION ALL SELECT 111, 'TrE_StawkaPodPrzedKorekta', 'Stawka VAT oryginalu (%)', '0,5,23', 'Stawka_VAT_Przed_Korekta', '=', 'Tak', '', ''
UNION ALL SELECT 112, 'TrE_FlagaVatPrzedKorekta', 'Rozroznienie stawki zero oryginalu', '0,1', 'Flaga_VAT_Przed_Korekta', 'CASE: 0=Zwolniony, 1=Opodatkowany, 2=Nie podlega, ELSE Nieznane(val); w danych tylko 0/1 ale CASE kompletny dla spojnosci z FlagaVat', 'Tak', '', ''
UNION ALL SELECT 113, 'TrE_ZrodlowaPrzedKorekta', 'Stawka poczatkowa oryginalu', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 114, 'TrE_AkcyzaPrzedKorekta', 'Stawka akcyzowa oryginalu', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 115, 'TrE_PrzyczynaKorekty', 'Tresc przyczyny korekty', 'rabat,skonto,Zwrot', 'Przyczyna_Korekty', 'NULLIF(RTRIM, pusty string) -> NULL gdy puste', 'Tak', '46 distinct wartosci; NULL gdy nie korekta', ''
UNION ALL SELECT 116, 'TrE_KatDatyOP', 'Kategoria daty obowiazku podatkowego', '0,2,3,11,12,13', '-', '-', 'Nie', 'Specjalistyczne pole VAT - poza zakresem widoku', ''
UNION ALL SELECT 117, 'TrE_RodzajKosztu', 'Rodzaj kosztu dodatkowego', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 118, 'TrE_PakietTwgNumer', '', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 119, 'TrE_PakietTwgTyp', '', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 120, 'TrE_RabatOpeGen', 'Rabat wygenerowany przez operatora', '0,3,8.18,15,20', 'Rabat_Operator', '=', 'Tak', '', ''
UNION ALL SELECT 121, 'TrE_PakietWymaganaPoz', 'Wymagana pozycja pakietu', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 122, 'TrE_SentId', 'Identyfikator dokumentu SENT', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 123, 'TrE_Nagroda', '', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 124, 'TrE_OperatorPOS', 'GIDNumer operatora POS dodajacego element', '0,18,54,55,56,57,58', '-', '-', 'Nie', 'Dane POS - specjalistyczne, poza zakresem widoku', ''
UNION ALL SELECT 125, 'TrE_SentElemId', 'Identyfikator elementu dokumentu SENT', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 126, 'TrE_GUID', 'GUID elementu z POS', 'UUID...', '-', '-', 'Nie', 'Techniczny identyfikator POS - nie unikalny per wiersz', ''
UNION ALL SELECT 127, 'TrE_OplataSpozFlaga', 'Oplata spozywcza', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 128, 'TrE_StawkaCukierStala', 'Stala oplata cukrowa', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 129, 'TrE_StawkaCukierZmienna', 'Zmienna oplata cukrowa', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 130, 'TrE_StawkaKofeina', 'Oplata za kofeine', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
UNION ALL SELECT 131, 'TrE_Bon', '1=Bon', '0', '-', '-', 'Nie', 'COUNT DISTINCT=1 (0)', ''
ORDER BY Kolejnosc
