SELECT 1 AS Kolejnosc, 'Twr_GIDTyp' AS CDN_Pole, 'ID Typu (zawsze 16)' AS Opis_w_dokumentacji, '16' AS Przykladowe_wartosci, '-' AS Alias_w_widoku, 'stala techniczna' AS Transformacja, 'Nie' AS Uwzglednic, 'Stala techniczna' AS Uzasadnienie, '' AS Komentarz_Usera
UNION ALL SELECT 2,'Twr_GIDFirma','ID firmy','1464833','-','stala techniczna','Nie','Stala techniczna',''
UNION ALL SELECT 3,'Twr_GIDNumer','ID rekordu — unikalny numer karty towaru','0..10122','ID_Towaru','bez zmian','Tak','Klucz glowny widoku',''
UNION ALL SELECT 4,'Twr_GIDLp','Zawsze 0','0','-','stala','Nie','Stala techniczna',''
UNION ALL SELECT 5,'Twr_Typ','Typ elementu (Towar/Produkt/Koszt/Usluga)','1,2,3,4','Typ','CASE 1=Towar 2=Produkt 3=Koszt 4=Usluga 6=? ELSE Nieznane','Tak','Typ kartoteki towarowej',''
UNION ALL SELECT 6,'Twr_Kod','Kod towaru','A-VISTA','Kod','bez zmian','Tak','Kod towaru — identyfikator biznesowy',''
UNION ALL SELECT 7,'Twr_KodFormat','Format kodu (zawsze pusty)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 8,'Twr_FPPKod','FPP kod (zawsze pusty)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 9,'Twr_Nazwa','Nazwa towaru','A-Vista, ...','Nazwa','bez zmian','Tak','Pelna nazwa towaru',''
UNION ALL SELECT 10,'Twr_Nazwa1','Nazwa skrocona / dodatkowa (36 distinct)','','Nazwa1','bez zmian','Tak','Dodatkowa nazwa — 36 unikalnych wartosci',''
UNION ALL SELECT 11,'Twr_Certyfikat','Certyfikat (zawsze pusty)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 12,'Twr_Sww','SWW (zawsze pusty)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 13,'Twr_Ean','Kod EAN','','EAN','bez zmian','Tak','Kod kreskowy towaru',''
UNION ALL SELECT 14,'Twr_Jm','Jednostka miary','szt.','JM','bez zmian','Tak','Jednostka miary sprzedazy (6 wartosci)',''
UNION ALL SELECT 15,'Twr_Waga','Waga (zawsze 0)','0.000','-','stala','Nie','Stala 0 dla wszystkich',''
UNION ALL SELECT 16,'Twr_WJm','JM wagi (zawsze pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 17,'Twr_JmFormat','Format JM','0,2,3,4','JM_Format','bez zmian — do zbadania znaczenia','Tak','4 wartosci — znaczenie wymaga dokumentacji',''
UNION ALL SELECT 18,'Twr_IloscZam','Ilosc zamowienia (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 19,'Twr_IloscMin','Ilosc minimalna (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 20,'Twr_IloscMax','Ilosc maksymalna (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 21,'Twr_Ubytek','Ubytek (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 22,'Twr_Prog','Prog (stala 1)','1','-','stala','Nie','Stala 1',''
UNION ALL SELECT 23,'Twr_Upust','Upust (stala 1)','1','-','stala','Nie','Stala 1',''
UNION ALL SELECT 24,'Twr_UpustData','Upust data (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 25,'Twr_UpustDataOd','Upust data od (stala 81112)','81112','-','stala','Nie','Stala',''
UNION ALL SELECT 26,'Twr_UpustDataDo','Upust data do (stala 81112)','81112','-','stala','Nie','Stala',''
UNION ALL SELECT 27,'Twr_UpustGodz','Upust godzina (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 28,'Twr_UpustGodzOd','Upust godzina od (stala 6000)','6000','-','stala','Nie','Stala',''
UNION ALL SELECT 29,'Twr_UpustGodzDo','Upust godzina do (stala 6000)','6000','-','stala','Nie','Stala',''
UNION ALL SELECT 30,'Twr_AutoZam','Auto zamowienie (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 31,'Twr_IloscAZam','Ilosc auto zamowienia (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 32,'Twr_CzasDst','Czas dostawy (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 33,'Twr_CenaSpr','Cena sprzedazy — typ','1,3,6','Cena_Sprzedazy_Typ','bez zmian — do zbadania znaczenia','Tak','3 wartosci — cena 1/3/6',''
UNION ALL SELECT 34,'Twr_JmDomyslna','Domyslna JM','0..6','JM_Domyslna_Id','bez zmian','Tak','FK do tabeli JM — 6 wartosci',''
UNION ALL SELECT 35,'Twr_DstDomyslny','Domyslny dostawca','0,1,2,3,4','Dostawca_Domyslny','bez zmian — do zbadania','Tak','Typ domyslnego dostawcy',''
UNION ALL SELECT 36,'Twr_RozliczMag','Rozlicz magazyn (stala 1)','1','-','stala','Nie','Stala 1',''
UNION ALL SELECT 37,'Twr_Zakup','Zakup (stala 0)','0','-','stala','Nie','Stala 0 — nieuzywane',''
UNION ALL SELECT 38,'Twr_Sprzedaz','Sprzedaz (stala 0)','0','-','stala','Nie','Stala 0 — nieuzywane',''
UNION ALL SELECT 39,'Twr_GrupaPod','Grupa VAT zakup','A,B,D','Grupa_VAT_Zakup','bez zmian','Tak','Grupa podatkowa zakupu',''
UNION ALL SELECT 40,'Twr_Akcyza','Akcyza (stala 0)','0.00','-','stala','Nie','Stala 0',''
UNION ALL SELECT 41,'Twr_OpeTyp','Typ GID operatora (stala 128)','128','-','stala','Nie','Para z OpeNumer',''
UNION ALL SELECT 42,'Twr_OpeFirma','Firma operatora (stala)','1464833','-','stala','Nie','Stala firma',''
UNION ALL SELECT 43,'Twr_OpeNumer','Operator tworzacy (GID)','','ID_Operatora_Tworzacego','JOIN CDN.OpeKarty ON Ope_GIDNumer — Ope_Ident + Ope_Nazwisko','Tak','Operator ktory utworzyl karte towaru',''
UNION ALL SELECT 44,'Twr_OpeLp','LP operatora (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 45,'Twr_PrcTyp','PRC typ (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 46,'Twr_PrcFirma','PRC firma (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 47,'Twr_PrcNumer','PRC numer (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 48,'Twr_PrcLp','PRC LP (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 49,'Twr_KontaktTyp','Kontakt typ (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 50,'Twr_KontaktZa','Kontakt za (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 51,'Twr_KontaktJC','Kontakt JC (stala 1)','1','-','stala','Nie','Stala 1',''
UNION ALL SELECT 52,'Twr_Okresowy','Okresowy (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 53,'Twr_Cel','Cel (stala pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 54,'Twr_Atrybut1','Atrybut 1 (stala pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 55,'Twr_Format1','Format 1 (stala 1)','1','-','stala','Nie','Stala 1',''
UNION ALL SELECT 56,'Twr_Wartosc1','Wartosc 1 (stala pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 57,'Twr_Atrybut2','Atrybut 2 (stala pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 58,'Twr_Format2','Format 2 (stala 1)','1','-','stala','Nie','Stala 1',''
UNION ALL SELECT 59,'Twr_Wartosc2','Wartosc 2 (stala pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 60,'Twr_Atrybut3','Atrybut 3 (stala pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 61,'Twr_Format3','Format 3 (stala 1)','1','-','stala','Nie','Stala 1',''
UNION ALL SELECT 62,'Twr_Wartosc3','Wartosc 3 (stala pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 63,'Twr_Punkty','Punkty (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 64,'Twr_Koncesja','Koncesja (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 65,'Twr_Konto1','Konto 1 (pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 66,'Twr_Konto2','Konto 2 (pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 67,'Twr_Konto3','Konto 3 (pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 68,'Twr_Polozenie','Polozenie (pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 69,'Twr_Katalog','Katalog (4 wartosci)','P-100, EAN-like','Katalog','bez zmian — zbadac znaczenie','Tak','Kod katalogu — 4 wartosci w tym puste',''
UNION ALL SELECT 70,'Twr_WCenniku','W cenniku','0,1','W_Cenniku','CASE 1=Tak 0=Nie','Tak','Czy towar widoczny w cenniku',''
UNION ALL SELECT 71,'Twr_EdycjaNazwy','Edycja nazwy dozwolona','0,1','Edycja_Nazwy','CASE 1=Tak 0=Nie','Tak','Flaga edytowalnosci nazwy',''
UNION ALL SELECT 72,'Twr_BezRabatu','Bez rabatu','0,1','Bez_Rabatu','CASE 1=Tak 0=Nie','Tak','Czy towar bez rabatu',''
UNION ALL SELECT 73,'Twr_KopiujOpis','Kopiuj opis (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 74,'Twr_URL','URL (stala pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 75,'Twr_Warunek','Warunek (stala pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 76,'Twr_ObjetoscL','Objetosc L (stala 0)','0.00','-','stala','Nie','Stala 0',''
UNION ALL SELECT 77,'Twr_ObjetoscM','Objetosc M (stala 1)','1','-','stala','Nie','Stala 1',''
UNION ALL SELECT 78,'Twr_LastModL','Ostatnia modyfikacja L (Clarion TS)','','Data_Modyfikacji_L','DATEADD(ss, val, 1990-01-01) — NULL gdy 0','Tak','Timestamp ostatniej modyfikacji (liczba)',''
UNION ALL SELECT 79,'Twr_LastModO','Ostatnia modyfikacja O (Clarion TS)','','Data_Modyfikacji_O','DATEADD(ss, val, 1990-01-01) — NULL gdy 0','Tak','Timestamp modyfikacji O',''
UNION ALL SELECT 80,'Twr_LastModC','Ostatnia modyfikacja C (Clarion TS)','','Data_Modyfikacji_C','DATEADD(ss, val, 1990-01-01) — NULL gdy 0','Tak','Timestamp modyfikacji C',''
UNION ALL SELECT 81,'Twr_TerminZwrotu','Termin zwrotu (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 82,'Twr_ZakupAutoryz','Zakup autoryzowany','0,1','Zakup_Autoryzowany','CASE 1=Tak 0=Nie','Tak','Wymaga autoryzacji przy zakupie',''
UNION ALL SELECT 83,'Twr_MagTyp','Typ GID magazynu (stala 208)','208','-','stala','Nie','Para z MagNumer',''
UNION ALL SELECT 84,'Twr_MagFirma','Firma magazynu (stala)','1464833','-','stala','Nie','Stala firma',''
UNION ALL SELECT 85,'Twr_MagNumer','Magazyn domyslny (GID)','1,4,5,9,10','ID_Magazynu','JOIN CDN.Magazyny na Mag_GIDNumer — Mag_Nazwa/Mag_Skrot','Tak','Domyslny magazyn towaru',''
UNION ALL SELECT 86,'Twr_MagLp','LP magazynu (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 87,'Twr_MarzaMin','Marza minimalna (stala 0)','0.00','-','stala','Nie','Stala 0',''
UNION ALL SELECT 88,'Twr_KosztUslugi','Koszt uslugi (stala 0)','0.00','-','stala','Nie','Stala 0',''
UNION ALL SELECT 89,'Twr_KosztUTyp','Typ kosztu uslugi','0,1','Koszt_Uslugi_Typ','bez zmian — do zbadania','Tak','Typ kosztu: 2 wartosci',''
UNION ALL SELECT 90,'Twr_CzasWykonania','Czas wykonania (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 91,'Twr_CzasWykonaniaJedn','JM czasu (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 92,'Twr_Clo','Clo (stala 0)','0.00','-','stala','Nie','Stala 0',''
UNION ALL SELECT 93,'Twr_PodatekImp','Podatek importowy (stala 0)','0.00','-','stala','Nie','Stala 0',''
UNION ALL SELECT 94,'Twr_StanInfoLimit','Stan info limit (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 95,'Twr_StanInfoMax','Stan info max (stala 0)','0.0000','-','stala','Nie','Stala 0',''
UNION ALL SELECT 96,'Twr_StanInfoProcent','Stan info procent (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 97,'Twr_Aktywna','Aktywna (stala 0 — ANOMALIA)','0','-','stala — zawsze 0 dla TwrGIDNumer>0','Nie','Stala 0 — faktyczny status w Twr_Archiwalny',''
UNION ALL SELECT 98,'Twr_Wsk','Wsk (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 99,'Twr_CCKTyp','Typ klasy cechy GID','0,192','-','stala techniczna','Nie','Para z CCKNumer',''
UNION ALL SELECT 100,'Twr_CCKFirma','Firma klasy cechy','0,1464833','-','stala techniczna','Nie','Stala firma',''
UNION ALL SELECT 101,'Twr_CCKNumer','Klasa cechy (GID)','0,1','ID_Klasy_Cechy','bez zmian — CASE 0=brak else val','Tak','FK do CDN.CechyKlasy (typ 192) — 2 wartosci',''
UNION ALL SELECT 102,'Twr_CCKLp','LP klasy cechy (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 103,'Twr_PrdTyp','Typ GID producenta','0,32','-','stala techniczna','Nie','Para z PrdNumer',''
UNION ALL SELECT 104,'Twr_PrdFirma','Firma producenta','0,1464833','-','stala techniczna','Nie','Stala firma',''
UNION ALL SELECT 105,'Twr_PrdNumer','Producent (GID Kontrahenta)','','ID_Producenta','JOIN CDN.KntKarty na Knt_GIDNumer — Knt_Kod + Knt_Nazwa1','Tak','Producent = FK do Kontrahenta (GIDTyp=32)',''
UNION ALL SELECT 106,'Twr_PrdLp','LP producenta (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 107,'Twr_OpeTypM','Typ GID op.modyfikujacego (stala 128)','128','-','stala','Nie','Para z OpeNumerM',''
UNION ALL SELECT 108,'Twr_OpeFirmaM','Firma op.modyfikujacego (stala)','1464833','-','stala','Nie','Stala firma',''
UNION ALL SELECT 109,'Twr_OpeNumerM','Operator modyfikujacy (GID)','','ID_Operatora_Modyfikujacego','JOIN CDN.OpeKarty ON Ope_GIDNumer — Ope_Ident','Tak','Operator ktory ostatnio modyfikowal karte',''
UNION ALL SELECT 110,'Twr_OpeLpM','LP op.modyfikujacego (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 111,'Twr_PCN','PCN (stala pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 112,'Twr_Notowania','Notowania (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 113,'Twr_WagaBrutto','Waga brutto (stala 0)','0.000','-','stala','Nie','Stala 0',''
UNION ALL SELECT 114,'Twr_WJmBrutto','JM wagi brutto (pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 115,'Twr_StawkaPod','Stawka VAT zakup','0.00,8.00,23.00','Stawka_VAT_Zakup','bez zmian (numeric)','Tak','Stawka VAT przy zakupie',''
UNION ALL SELECT 116,'Twr_FlagaVat','Flaga VAT zakup','0,1','Flaga_VAT_Zakup','CASE 1=Tak 0=Nie','Tak','Flaga VAT zakupu',''
UNION ALL SELECT 117,'Twr_Zrodlowa','Zrodlowa (stala 0)','0.00','-','stala','Nie','Stala 0',''
UNION ALL SELECT 118,'Twr_GrupaPodSpr','Grupa VAT sprzedaz','A,B,D','Grupa_VAT_Sprzedaz','bez zmian','Tak','Grupa podatkowa sprzedazy',''
UNION ALL SELECT 119,'Twr_StawkaPodSpr','Stawka VAT sprzedaz','0.00,8.00,23.00','Stawka_VAT_Sprzedaz','bez zmian (numeric)','Tak','Stawka VAT przy sprzedazy',''
UNION ALL SELECT 120,'Twr_FlagaVatSpr','Flaga VAT sprzedaz','0,1','Flaga_VAT_Sprzedaz','CASE 1=Tak 0=Nie','Tak','Flaga VAT sprzedazy',''
UNION ALL SELECT 121,'Twr_ZrodlowaSpr','Zrodlowa sprzedaz (stala 0)','0.00','-','stala','Nie','Stala 0',''
UNION ALL SELECT 122,'Twr_Licencja','Licencja (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 123,'Twr_Blokada','Blokada (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 124,'Twr_Archiwalny','Archiwalny (faktyczny status aktywnosci)','0,1','Archiwalny','CASE 1=Tak 0=Nie','Tak','UWAGA: Twr_Aktywna stala=0 — status aktywnosci tu',''
UNION ALL SELECT 125,'Twr_JMCalkowita','Ilosc tylko calkowita','0,1','JM_Calkowita','CASE 1=Tak 0=Nie','Tak','Czy ilosc musi byc calkowita',''
UNION ALL SELECT 126,'Twr_Oddzialowy','Oddzialowy (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 127,'Twr_JmDomyslnaZak','Domyslna JM zakup','0,1,2','JM_Domyslna_Zakup','bez zmian — znaczenie do sprawdzenia','Tak','Domyslna JM dla operacji zakupu',''
UNION ALL SELECT 128,'Twr_KrajPoch','Kraj pochodzenia','PL lub pusty','Kraj_Pochodzenia','bez zmian','Tak','Kraj pochodzenia towaru',''
UNION ALL SELECT 129,'Twr_WspFin','Wspolczynnik finansowy (stala 0)','0.0000','-','stala','Nie','Stala 0',''
UNION ALL SELECT 130,'Twr_PobierzWgCech','Pobierz wg cech (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 131,'Twr_Kaucja','Kaucja (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 132,'Twr_SkNId','SkNId (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 133,'Twr_RejWyposazenia','Rejestr wyposazenia (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 134,'Twr_OkresGwarancji','Okres gwarancji (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 135,'Twr_GrupaWyposazenia','Grupa wyposazenia (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 136,'Twr_ProdTechnologia','Technologia (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 137,'Twr_ProdAktualnaWersja','Aktualna wersja (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 138,'Twr_TwZOdNajwiekszego','TwZ od najw. (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 139,'Twr_DataUtworzenia','Data utworzenia (Clarion TS)','1052041462..1142161764','Data_Utworzenia','DATEADD(ss, val, 1990-01-01) — NULL gdy 0','Tak','Timestamp utworzenia karty towaru',''
UNION ALL SELECT 140,'Twr_WymJm','JM wymiarow','m,cm','JM_Wymiarow','bez zmian','Tak','Jednostka miary wymiarow (2 wartosci)',''
UNION ALL SELECT 141,'Twr_PartiaDataW','Partia data W (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 142,'Twr_TerminW','Termin W (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 143,'Twr_PartiaDostawa','Partia dostawa (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 144,'Twr_NrSeryjnyZCechy','Nr seryjny z cechy (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 145,'Twr_ESklep','E-Sklep (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 146,'Twr_StawkaKGO','Stawka KGO (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 147,'Twr_DostawaEAN','Dostawa EAN','0,1','Dostawa_EAN','CASE 1=Tak 0=Nie','Tak','EAN przy dostawie',''
UNION ALL SELECT 148,'Twr_MarkaId','Marka ID (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 149,'Twr_RejestrujUrzadzenie','Rejestruj urzadzenie (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 150,'Twr_RodzajUrzadzenia','Rodzaj urzadzenia (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 151,'Twr_OpisUrzadzenia','Opis urzadzenia (pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 152,'Twr_KategoriaABCXYZ','Kategoria ABCXYZ (pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 153,'Twr_RodzajId','Rodzaj ID (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 154,'Twr_MobSpr','Mobile sprzedaz','0,1','Mobile_Sprzedaz','CASE 1=Tak 0=Nie','Tak','Dostepny w mobile sprzedaz',''
UNION ALL SELECT 155,'Twr_PLM','PLM (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 156,'Twr_JMBlokujZmiane','Blokuj zmiane JM','0,1','JM_Blokuj_Zmiane','CASE 1=Tak 0=Nie','Tak','Blokada zmiany JM',''
UNION ALL SELECT 157,'Twr_AnalizaABCXYZ','Analiza ABC/XYZ','0,1','Analiza_ABCXYZ','CASE 1=Tak 0=Nie','Tak','Czy uwzgledniany w analizie ABC/XYZ',''
UNION ALL SELECT 158,'Twr_Zlom','Zlom (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 159,'Twr_JMiSklep','JM i sklep','0,1','JM_Sklep','CASE 1=Tak 0=Nie','Tak','Flaga JM sklep',''
UNION ALL SELECT 160,'Twr_JMPulpitKnt','JM pulpit kontrahenta','0,1','JM_Pulpit_Knt','CASE 1=Tak 0=Nie','Tak','Flaga JM pulpit klienta',''
UNION ALL SELECT 161,'Twr_JMMobSpr','JM mobile sprzedaz (6 wartosci)','','JM_Mobile_Sprzedaz_Id','bez zmian','Tak','JM dla mobile sprzedaz (6 wartosci)',''
UNION ALL SELECT 162,'Twr_PIADostepnoscFlaga','PIA dostepnosc','0,8','PIA_Dostepnosc','bez zmian — do zbadania','Tak','Flaga dostepnosci PIA',''
UNION ALL SELECT 163,'Twr_ObowPodSprId','Obowiazek pod. sprzedaz (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 164,'Twr_ObowPodZakId','Obowiazek pod. zakup (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 165,'Twr_RodzajKosztu','Rodzaj kosztu (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 166,'Twr_JMDopelnianiaMobSpr','JM dopelniania mobile (6 wartosci)','','JM_Dopelniania_Mobile_Id','bez zmian','Tak','JM dla dopelniania mobile',''
UNION ALL SELECT 167,'Twr_Techniczna1','Techniczna 1 (pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 168,'Twr_Techniczna2','Techniczna 2 (pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 169,'Twr_Techniczna3','Techniczna 3 (pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 170,'Twr_Techniczna4','Techniczna 4 (pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 171,'Twr_Obcy','Obcy (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 172,'Twr_TechnicznaDec1','Techniczna Dec1 (13 wartosci)','','Techniczna_Dec1','bez zmian','Tak','Techniczna wartosc decimalna — 13 roznych wartosci',''
UNION ALL SELECT 173,'Twr_MrpId','MRP ID (1172 distinct)','','MRP_Id','bez zmian — CASE 0=NULL else val','Tak','FK do systemu MRP — 1172 roznych wartosci',''
UNION ALL SELECT 174,'Twr_MrpEoq','MRP EOQ (stala 0)','0.0000','-','stala','Nie','Stala 0',''
UNION ALL SELECT 175,'Twr_MrpZaok','MRP zaokraglenie (stala 0)','0.0000','-','stala','Nie','Stala 0',''
UNION ALL SELECT 176,'Twr_AutonumeracjaKod','Kod autonumeracji','pusty lub NIEO','Autonumeracja_Kod','bez zmian','Tak','Kod schematu autonumeracji',''
UNION ALL SELECT 177,'Twr_AutonumeracjaLiczba','Liczba autonumeracji (110 distinct)','','Autonumeracja_Liczba','bez zmian','Tak','Licznik autonumeracji',''
UNION ALL SELECT 178,'Twr_WysylaniePartiiMobSpr','Wysylanie partii mobile','0,1','Wysylanie_Partii_Mobile','CASE 1=Tak 0=Nie','Tak','Wysylanie partii w mobile',''
UNION ALL SELECT 179,'Twr_DodEleZez','Dodaj elementy zezwolenia','0,1,2','Dod_Elementy_Zezwolenia','bez zmian — do zbadania','Tak','3 wartosci — typ zezwolenia',''
UNION ALL SELECT 180,'Twr_KodOdpadu','Kod odpadu (stala pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 181,'Twr_MPP','MPP (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 182,'Twr_GrupaJpk','Grupa JPK (pusta)','','-','stala','Nie','Stala pusta',''
UNION ALL SELECT 183,'Twr_OplataSpozFlaga','Oplata spoz. flaga (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 184,'Twr_StawkaCukierStala','Stawka cukier stala (stala 0)','0.00','-','stala','Nie','Stala 0',''
UNION ALL SELECT 185,'Twr_StawkaCukierZmienna','Stawka cukier zmienna (stala 0)','0.00','-','stala','Nie','Stala 0',''
UNION ALL SELECT 186,'Twr_StawkaKofeina','Stawka kofeina (stala 0)','0.00','-','stala','Nie','Stala 0',''
UNION ALL SELECT 187,'Twr_ZawartoscCukru','Zawartosc cukru (stala 0)','0.00','-','stala','Nie','Stala 0',''
UNION ALL SELECT 188,'Twr_OplataSpozPrzeliczL','Oplata spoz. L (stala 1)','1','-','stala','Nie','Stala 1',''
UNION ALL SELECT 189,'Twr_OplataSpozPrzeliczM','Oplata spoz. M (stala 1)','1','-','stala','Nie','Stala 1',''
UNION ALL SELECT 190,'Twr_OplataSpozDostawyTyp','Oplata spoz. typ dostawy (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 191,'Twr_OplataSpozDostawyFlaga','Oplata spoz. flaga dostawy (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 192,'Twr_OplataSpozNrPartii','Oplata spoz. nr partii (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 193,'Twr_OplataSpozNrPartiiAtrybut','Oplata spoz. atrybut partii (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 194,'Twr_JLogWMS','JLog WMS (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 195,'Twr_Bon','Bon (stala 0)','0','-','stala','Nie','Stala 0',''
UNION ALL SELECT 196,'[TwrGrupyDom] Nazwa grupy domowej','Nazwa grupy domowej towaru (JOIN TwrGrupyDom TGD_GIDTyp=16)','','Grupa_Domowa','LEFT JOIN CDN.TwrGrupyDom TGD na TGD_TwrTyp+TwrNumer, TGD_GIDTyp=16 → JOIN definicja TGD_GIDTyp=-16 na TGD_GrpNumer','Tak','Kategoria domowa towaru z hierarchii grup',''
UNION ALL SELECT 197,'[OpeKarty] Ident operatora tworzacego','Kod operatora tworzacego (z CDN.OpeKarty)','','Operator_Tworzacy','JOIN CDN.OpeKarty op1 ON op1.Ope_GIDNumer = Twr_OpeNumer','Tak','Identyfikator operatora ktory dodal karte',''
UNION ALL SELECT 198,'[OpeKarty] Ident operatora modyfikujacego','Kod operatora modyfikujacego (z CDN.OpeKarty)','','Operator_Modyfikujacy','JOIN CDN.OpeKarty op2 ON op2.Ope_GIDNumer = Twr_OpeNumerM','Tak','Operator ostatnio modyfikujacy karte',''
UNION ALL SELECT 199,'[KntKarty] Kod producenta','Kod kontrahenta-producenta (z CDN.KntKarty)','','Producent_Kod','LEFT JOIN CDN.KntKarty knt ON knt.Knt_GIDNumer = Twr_PrdNumer AND Twr_PrdNumer > 0','Tak','Producent towaru jako kontrahent',''
UNION ALL SELECT 200,'[Magazyny] Nazwa magazynu domyslnego','Nazwa magazynu (z CDN.Magazyny)','','Magazyn_Domyslny','LEFT JOIN CDN.Magazyny mag ON mag.Mag_GIDNumer = Twr_MagNumer AND Twr_MagNumer > 0','Tak','Domyslny magazyn dla towaru',''
