SELECT 1 AS Kolejnosc, 'ZaN_GIDTyp' AS CDN_Pole, 'Typ dokumentu (zawsze 960 = Zamowienie)' AS Opis_w_dokumentacji, '960' AS Przykladowe_wartosci, '-' AS Alias_w_widoku, 'stala — zawsze 960' AS Transformacja, 'Nie' AS Uwzglednic, 'Stala techniczna — rowna dla wszystkich wierszy' AS Uzasadnienie, '' AS Komentarz_Usera
UNION ALL SELECT 2,'ZaN_GIDFirma','ID firmy','1464833','-','stala techniczna','Nie','Stala techniczna',''
UNION ALL SELECT 3,'ZaN_GIDNumer','Identyfikator dokumentu (GID) — unikalny numer naglowka','38, 41','ID_Zamowienia','bez zmian','Tak','Klucz glowny widoku',''
UNION ALL SELECT 4,'ZaN_GIDLp','Zawsze rowne 0','0','-','stala','Nie','Stala techniczna',''
UNION ALL SELECT 5,'ZaN_ZrdTyp','Typ dokumentu zrodlowego','960','-','ZWERYFIKOWANE: ZrdNumer = GIDNumer dla wszystkich 12022 rekordow — pole nie wskazuje zrodla','Nie','Samoodniesienie — brak informacji dodatkowej',''
UNION ALL SELECT 6,'ZaN_ZrdFirma','ID firmy dokumentu zrodlowego','1464833','-','techniczne','Nie','Para z ZrdNumer',''
UNION ALL SELECT 7,'ZaN_ZrdNumer','Identyfikator dokumentu zrodlowego','33, 42','','ZWERYFIKOWANE: zawsze rowny ZaN_GIDNumer (samoodniesienie). Link ZZ->ZS przez CDN.ZamZamLinki — nie przez to pole.','Nie','Samoodniesienie — 0 rekordow roznych od GIDNumer',''
UNION ALL SELECT 8,'ZaN_ZrdLp','LP dokumentu zrodlowego','0','-','techniczne','Nie','LP techniczne',''
UNION ALL SELECT 9,'ZaN_KorTyp','Typ dokumentu korekcyjnego','0','','2/12022 nonzero','Nie','Zbyt rzadkie dla widoku BI',''
UNION ALL SELECT 10,'ZaN_KorFirma','ID firmy korekty','0','-','techniczne','Nie','Techniczne',''
UNION ALL SELECT 11,'ZaN_KorNumer','Numer dokumentu korekcyjnego (GID)','0','ID_Korekty','2/12022 nonzero — inline numer korekty mozliwy','Nie','Zbyt rzadkie dla widoku BI',''
UNION ALL SELECT 12,'ZaN_KorLp','LP korekty','0','-','techniczne','Nie','LP techniczne',''
UNION ALL SELECT 13,'ZaN_KntTyp','Typ GID kontrahenta','0, 32','-','techniczne','Nie','Para z KntNumer',''
UNION ALL SELECT 14,'ZaN_KntFirma','ID firmy kontrahenta','0, 1464833','-','techniczne','Nie','Firma techniczna',''
UNION ALL SELECT 15,'ZaN_KntNumer','Kontrahent (ID)','2362, 2175, 0','ID_Kontrahenta','CASE WHEN = 0 THEN NULL ELSE val — JOIN CDN.KntKarty','Tak','FK do CDN.KntKarty — 10742/12022 wypelnione',''
UNION ALL SELECT 16,'ZaN_KntLp','LP osoby odpowiedzialnej za dokument','0','-','techniczne','Nie','Zbyt szczegolowe',''
UNION ALL SELECT 17,'ZaN_KnATyp','Typ adresu kontrahenta','896, 0, 864','-','techniczne','Nie','Para z KnANumer',''
UNION ALL SELECT 18,'ZaN_KnAFirma','ID firmy adresu','1464833, 0','-','techniczne','Nie','Firma techniczna',''
UNION ALL SELECT 19,'ZaN_KnANumer','Adres kontrahenta (ID)','2540, 2556','ID_Adresu_Knt','JOIN CDN.KntAdresy — KnA_Akronim + KnA_Miasto + KnA_KodP + KnA_Ulica','Tak','Adres korespondencyjny kontrahenta',''
UNION ALL SELECT 20,'ZaN_KnALp','LP adresu','0','-','techniczne','Nie','LP techniczne',''
UNION ALL SELECT 21,'ZaN_AkwTyp','Typ GID akwizytora','32, 8224, 0','-','techniczne','Nie','Para z AkwNumer',''
UNION ALL SELECT 22,'ZaN_AkwFirma','ID firmy akwizytora','0, 1464833','-','techniczne','Nie','Firma techniczna',''
UNION ALL SELECT 23,'ZaN_AkwNumer','Akwizytor (ID)','10, 19, 16','ID_Akwizytora','CASE WHEN = 0 THEN NULL — JOIN CDN.KntKarty (Knt_Akronim)','Tak','FK do CDN.KntKarty — 10649/12022 wypelnione',''
UNION ALL SELECT 24,'ZaN_AkwLp','LP akwizytora','8224, 0','-','techniczne','Nie','LP techniczne',''
UNION ALL SELECT 25,'ZaN_AdWTyp','Typ adresu wysylkowego','864, 896, 0','-','techniczne','Nie','Para z AdWNumer',''
UNION ALL SELECT 26,'ZaN_AdwFirma','ID firmy adresu wysylkowego','0, 1464833','-','techniczne','Nie','Firma techniczna',''
UNION ALL SELECT 27,'ZaN_AdWNumer','Adres wysylkowy (ID)','400, 1191, 0','ID_Adresu_Wysylki','JOIN CDN.KntAdresy — KnA_Akronim + KnA_Miasto + KnA_KodP + KnA_Ulica','Tak','Adres dostawy/wysylki',''
UNION ALL SELECT 28,'ZaN_AdWLp','LP adresu wysylkowego','0','-','techniczne','Nie','LP techniczne',''
UNION ALL SELECT 29,'ZaN_MagTyp','Typ magazynu domyslnego','208','-','techniczne','Nie','Para z MagNumer',''
UNION ALL SELECT 30,'ZaN_MagFirma','ID firmy magazynu','1464833','-','techniczne','Nie','Firma techniczna',''
UNION ALL SELECT 31,'ZaN_MagNumer','Magazyn domyslny (ID)','29, 21, 6','ID_Magazynu','JOIN CDN.Magazyny — MAG_Kod + MAG_Nazwa','Tak','FK do CDN.Magazyny — 12021/12022',''
UNION ALL SELECT 32,'ZaN_MagLp','LP magazynu','0','-','techniczne','Nie','LP techniczne',''
UNION ALL SELECT 33,'ZaN_FormaNr','Forma platnosci (kod)','10, 20, 0','Forma_Platnosci_Kod','CASE: 10=Gotowka, 20=Przelew, 30=Kredyt, 40=Czek, 50=Karta, 60=Inne, 0=Brak ELSE Nieznane+val','Tak','Uzupelnienie FormaNazwa — CASE z dokumentacji',''
UNION ALL SELECT 34,'ZaN_FormaNazwa','Forma platnosci (nazwa)','Gotowka, Przelew','Forma_Platnosci','RTRIM(val)','Tak','Czytelna nazwa formy platnosci',''
UNION ALL SELECT 35,'ZaN_FormaRabat','Rabat z tytulu formy platnosci','0','','ZWERYFIKOWANE: 0/12022 nonzero — zawsze 0','Nie','Zawsze 0',''
UNION ALL SELECT 36,'ZaN_TerminPlatnosci','Termin platnosci (dni)','0, 7, 30, 60','Termin_Platnosci_Dni','bez zmian','Tak','Liczba dni do zaplaty',''
UNION ALL SELECT 37,'ZaN_ZamTyp','Typ zamowienia/oferty — 1280=ZS, 1152=ZZ, 768=Oferta sprzedazy, 640=Oferta zakupu, 2688=Zapyt.ofert.zakup, 2816=Zapyt.ofert.sprzedaz','1280, 1152, 768','Typ_Dokumentu','CASE: 640=Oferta zakupu, 768=Oferta sprzedazy, 1152=ZZ, 1280=ZS, 2688=Zapytanie ofert. zakup, 2816=Zapytanie ofert. sprzedaz ELSE Nieznane+val','Tak','Rozroznia ZS/ZZ/Oferty',''
UNION ALL SELECT 38,'ZaN_ZamRok','Rok zamowienia (skladowa numeru)','2023, 2024','(-> Numer_Dokumentu)','uzyty w inline construction — nie jako osobna kolumna','Nie','Wchodzi w Numer_Dokumentu',''
UNION ALL SELECT 39,'ZaN_ZamMiesiac','Miesiac zamowienia (skladowa numeru)','2, 3, 5','(-> Numer_Dokumentu)','uzyty w inline construction — nie jako osobna kolumna','Nie','Wchodzi w Numer_Dokumentu',''
UNION ALL SELECT 40,'ZaN_ZamSeria','Seria zamowienia (skladowa numeru)','SPKR, PH_2, OTO','(-> Numer_Dokumentu)','uzyty w inline construction — nie jako osobna kolumna','Nie','Wchodzi w Numer_Dokumentu',''
UNION ALL SELECT 41,'ZaN_ZamNumer','Numer kolejny (skladowa numeru)','4, 2, 5','(-> Numer_Dokumentu)','uzyty w inline construction — nie jako osobna kolumna','Nie','Wchodzi w Numer_Dokumentu',''
UNION ALL SELECT 42,'ZaN_ZamLp','Do pozniejszego wykorzystania — nieuzywane','0','-','nieuzywane wg dok.','Nie','Nieuzywane',''
UNION ALL SELECT 43,'ZaN_PomTyp','Typ dokumentu pomocniczego (potwierdzenia) — te same kody co ZamTyp + 3328/3136/3200','1280, 3328, 1152','(-> Numer_Potwierdzenia)','uzyty w inline construction Numer_Potwierdzenia','Nie','Wchodzi w Numer_Potwierdzenia',''
UNION ALL SELECT 44,'ZaN_PomRok','Rok dokumentu pomocniczego','2023, 2024','(-> Numer_Potwierdzenia)','uzyty w inline construction','Nie','Wchodzi w Numer_Potwierdzenia',''
UNION ALL SELECT 45,'ZaN_PomMiesiac','Miesiac dokumentu pomocniczego','9, 11, 8','(-> Numer_Potwierdzenia)','uzyty w inline construction','Nie','Wchodzi w Numer_Potwierdzenia',''
UNION ALL SELECT 46,'ZaN_PomSeria','Seria dokumentu pomocniczego','ZTHK, PH_5, PH_4','(-> Numer_Potwierdzenia)','uzyty w inline construction','Nie','Wchodzi w Numer_Potwierdzenia',''
UNION ALL SELECT 47,'ZaN_PomNumer','Numer dokumentu pomocniczego','5, 3, 9','(-> Numer_Potwierdzenia)','uzyty w inline construction','Nie','Wchodzi w Numer_Potwierdzenia',''
UNION ALL SELECT 48,'ZaN_PomLp','Nr wariantu oferty','0','-','techniczne','Nie','LP techniczne',''
UNION ALL SELECT 49,'ZaN_DokumentObcy','Nr zamowienia/oferty u kontrahenta (string)','','Dokument_Obcy','NULLIF(RTRIM(val), '''') — 1/12022 niepieste','Tak','Numer zamowienia po stronie kontrahenta — warto miec mimo rzadkiego wystepowania',''
UNION ALL SELECT 50,'ZaN_DokumentObcyCharset','Strona kodowa DokumentObcy','','-','techniczne','Nie','',''
UNION ALL SELECT 51,'ZaN_DokumentObcyP','Nr zapytania/potwierdzenia u kontrahenta','','-','NULLIF(RTRIM(val), '''')','Nie','Rzadkie — zbedne dla MVP',''
UNION ALL SELECT 52,'ZaN_DokumentObcyPCharset','Strona kodowa DokumentObcyP','','-','techniczne','Nie','',''
UNION ALL SELECT 53,'ZaN_ExpoNorm','Rodzaj transakcji: 0=Krajowa, 1=Inna zagr. VAT 0%, 2=Inna zagr. VAT dowolny, 6=WW dostawa VAT 0%, 7=WW dostawa VAT dowolny, 8=WW dost. trojstr. VAT 0%, 9=WW dost. trojstr. VAT dowolny, 10=WW nabycie VAT 0%, 11=WW nabycie VAT dowolny, 26=WSTO_EE','0, 1, 6','Rodzaj_Transakcji','CASE: 0=Krajowa, 1=Inna zagr. VAT 0%, 2=Inna zagr. VAT dowolny, 6=WW dostawa VAT 0%, 7=WW dostawa VAT dowolny, 8=WW dost. trojstr. VAT 0%, 9=WW dost. trojstr. VAT dowolny, 10=WW nabycie VAT 0%, 11=WW nabycie VAT dowolny, 12=WW nab. trojstr. VAT 0%, 13=WW nab. trojstr. VAT dowolny, 26=WSTO_EE ELSE Nieznane+val','Tak','Rodzaj transakcji w kontekscie VAT/eksportu',''
UNION ALL SELECT 54,'ZaN_Waluta','Symbol waluty transakcji','PLN, EUR','Waluta','bez zmian','Tak','Waluta zamowienia',''
UNION ALL SELECT 55,'ZaN_NrKursu','Numer kursu','1','-','techniczne','Nie','Technikalia kursu',''
UNION ALL SELECT 56,'ZaN_KursM','Kurs waluty (mianownik)','1, 100','Kurs_Waluty_M','bez zmian — mianownik','Tak','Kurs waluty — potrzebny przy walutach obcych',''
UNION ALL SELECT 57,'ZaN_KursL','Kurs waluty (licznik)','1.00, 429.30','Kurs_Waluty_L','bez zmian — licznik','Tak','Kurs waluty — licznik',''
UNION ALL SELECT 58,'ZaN_TypKursu','Typ kursu: 1=biezacy, 2=ustalony, 3=ustalony do daty waznosci potem biezacy','1','Typ_Kursu','CASE: 1=Biezacy, 2=Ustalony, 3=Ustalony do daty ELSE Nieznane+val','Tak','Rozroznia biezacy od ustalonego kursu',''
UNION ALL SELECT 59,'ZaN_WspolnaWaluta','Czy wymusic wspolna walute na elementach','0, 1','-','flaga — mala wartosc analityczna','Nie','Rzadko uzywane',''
UNION ALL SELECT 60,'ZaN_OpeTypW','Typ GID operatora wystawiajacego','128','-','techniczne','Nie','Para z OpeNumerW',''
UNION ALL SELECT 61,'ZaN_OpeFirmaW','ID firmy operatora wystawiajacego','1464833','-','techniczne','Nie','Firma techniczna',''
UNION ALL SELECT 62,'ZaN_OpeNumerW','Operator wystawiajacy (ID)','4, 12, 23','ID_Operatora_W','bez zmian + JOIN CDN.OpeKarty (Ope_Ident)','Tak','FK do CDN.OpeKarty',''
UNION ALL SELECT 63,'ZaN_OpeLpW','LP operatora wystawiajacego','0','-','techniczne','Nie','LP techniczne',''
UNION ALL SELECT 64,'ZaN_OpeTypM','Typ GID operatora modyfikujacego','128','-','techniczne','Nie','Para z OpeNumerM',''
UNION ALL SELECT 65,'ZaN_OpeFirmaM','ID firmy operatora modyfikujacego','1464833','-','techniczne','Nie','Firma techniczna',''
UNION ALL SELECT 66,'ZaN_OpeNumerM','Operator modyfikujacy (ID)','27, 10, 29','ID_Operatora_M','CASE WHEN = 0 THEN NULL + JOIN CDN.OpeKarty (Ope_Ident)','Tak','FK do CDN.OpeKarty — operator ktory modyfikowal',''
UNION ALL SELECT 67,'ZaN_OpeTypZ','Typ GID operatora zatwierdzajacego','0, 128','-','techniczne','Nie','Para z OpeNumerZ',''
UNION ALL SELECT 68,'ZaN_OpeFirmaZ','ID firmy operatora zatwierdzajacego','0, 1464833','-','techniczne','Nie','Firma techniczna',''
UNION ALL SELECT 69,'ZaN_OpeNumerZ','Operator zatwierdzajacy (ID)','27, 10, 26','ID_Operatora_Z','CASE WHEN = 0 THEN NULL + JOIN CDN.OpeKarty (Ope_Ident)','Tak','FK do CDN.OpeKarty — operator ktory zatwierdzal',''
UNION ALL SELECT 70,'ZaN_OpeLpZ','LP operatora zatwierdzajacego','0','-','techniczne','Nie','LP techniczne',''
UNION ALL SELECT 71,'ZaN_OpeTypP','Typ GID operatora potwierdzajacego zapytanie/potwierdzenie','0, 128','-','techniczne','Nie','Para z OpeNumerP',''
UNION ALL SELECT 72,'ZaN_OpeFirmaP','ID firmy','1464833, 0','-','techniczne','Nie','Firma techniczna',''
UNION ALL SELECT 73,'ZaN_OpeNumerP','Pomocn. operator zapyt./potwierdz.','23, 20, 30','-','powiazane z dok. pomocniczym (potwierdzenie) — zbedne dla MVP','Nie','Zbedne',''
UNION ALL SELECT 74,'ZaN_OpeLpP','LP','0','-','techniczne','Nie','LP techniczne',''
UNION ALL SELECT 75,'ZaN_ID','Identyfikator parametrow dokumentu','','-','techniczne','Nie','Stary identyfikator — null w danych',''
UNION ALL SELECT 76,'ZaN_Rabat','Rabat globalny (% lub kwotowy)','12.00, 3.00, 10.00, 0.00','Rabat_Globalny','CASE WHEN = 0 THEN NULL ELSE val — 2712/12022 nonzero','Tak','Realny rabat naglowkowy — 22% rekordow ma wartosc',''
UNION ALL SELECT 77,'ZaN_TypRabatu','Typ rabatu: 1=procentowy, 2=kwotowy','1','Typ_Rabatu','CASE: 1=Procentowy, 2=Kwotowy ELSE Nieznane+val','Tak','Kontekst do pola Rabat_Globalny',''
UNION ALL SELECT 78,'ZaN_SpDostawy','Opis sposobu dostawy','CEIM, JAS, Geodis, Pocztex','Sposob_Dostawy','NULLIF(RTRIM(val), '''') — 9578/12022 wypelnione','Tak','Firma kurierska / sposob dostawy',''
UNION ALL SELECT 79,'ZaN_CechaOpis','Cecha zamowienia','Wzory, SEZON, <Nieokreslona>','Cecha','NULLIF(NULLIF(RTRIM(val), ''<Nieokreslona>''), '''') — 8916/12022','Tak','Sezon/wzor/cecha handlowa',''
UNION ALL SELECT 80,'ZaN_DataZapytania','Data przyjecia zapytania ofertowego','','Data_Zapytania','Clarion DATE — 0/12022 nonzero w sample','Nie','Tylko dla zapytan — null w danych',''
UNION ALL SELECT 81,'ZaN_RealWCalosci','Czy realizacja tylko w calosci','0, 1','Zrealizowane_W_Calosci','CASE: 0=Nie, 1=Tak','Tak','4/12022 = Tak — wartosc informacyjna',''
UNION ALL SELECT 82,'ZaN_DataWystawienia','Data wystawienia oferty/zamowienia','81315, 81377','Data_Wystawienia','Clarion DATE: CASE WHEN =0 THEN NULL ELSE CAST(DATEADD(d,val,''18001228'') AS DATE)','Tak','Glowna data dokumentu',''
UNION ALL SELECT 83,'ZaN_DataRealizacji','Przewidywana data realizacji zamowienia','81377, 81461','Data_Realizacji','Clarion DATE: CASE WHEN =0 THEN NULL ELSE CAST(DATEADD(d,val,''18001228'') AS DATE)','Tak','Planowana data realizacji',''
UNION ALL SELECT 84,'ZaN_DataWaznosci','Data obowiazywania oferty/zamowienia','93890, 81247','Data_Waznosci','Clarion DATE: CASE WHEN =0 THEN NULL ELSE CAST(DATEADD(d,val,''18001228'') AS DATE)','Tak','Data waznosci — 93890 = sentinel bezterminowo',''
UNION ALL SELECT 85,'ZaN_DataPotwierdz','Data potwierdzenia zamowienia','81369, 81363, 0','Data_Potwierdzenia','Clarion DATE: CASE WHEN =0 THEN NULL ELSE CAST(DATEADD(d,val,''18001228'') AS DATE)','Tak','11984/12022 wypelnione',''
UNION ALL SELECT 86,'ZaN_DataAkceptacji','Data akceptacji zwrotnej klienta','','-','Clarion DATE — 0/12022 nonzero','Nie','Zawsze 0',''
UNION ALL SELECT 87,'ZaN_DataOdZam','Ilosc dni od daty zamowienia','','-','0/12022 nonzero','Nie','Zawsze 0',''
UNION ALL SELECT 88,'ZaN_Stan','Stan dokumentu (bitmask) — maska_archiw=16, maska_anulowane=32, base: 0=zapytanie, 1=oferta, 2=zamowienie, 3=potwierdzone, 4=zaakceptowane, 5=w realizacji','53, 21, 35, 51, 2, 3, 5, 1, 4','Stan_Zamowienia','CASE: 1=Oferta, 2=Zamowienie, 3=Potwierdzone, 4=Zaakceptowane, 5=W realizacji, 19=Odrzucone, 21=Zrealizowane, 35=Anulowane (potw.), 51=Anulowane arch.+potw., 53=Anulowane arch.+w real. ELSE Nieznane+val','Tak','Kluczowy status dokumentu',''
UNION ALL SELECT 89,'ZaN_Aktywny','Czy dok. aktywny/zablokowany na czas wystawiania','0, 4240','-','is_useful semantycznie — blokada edycji, nie status biznesowy','Nie','Techniczne — blokada edycyjna',''
UNION ALL SELECT 90,'ZaN_DokZwiazane','Wskaznik istnienia stowarzyszonych dok. (bitmask)','0, 16, 48, 96, 32','-','bitmask — nie FK','Nie','Nie jest FK — nie da sie rozlinkkowac do dokumentow',''
UNION ALL SELECT 91,'ZaN_LKopii','Pole nieuzywane','','-','wg dok. nieuzywane','Nie','Nieuzywane',''
UNION ALL SELECT 92,'ZaN_Wsk','Wskaznik zaznaczania (API)','','-','API marker','Nie','Techniczne API',''
UNION ALL SELECT 93,'ZaN_KnSTyp','Identyfikator osoby (Typ)','','-','techniczne — null w danych','Nie','Null',''
UNION ALL SELECT 94,'ZaN_KnSFirma','Identyfikator osoby (Firma)','','-','techniczne','Nie','Null',''
UNION ALL SELECT 95,'ZaN_KnSNumer','Identyfikator osoby (Numer)','','-','techniczne','Nie','Null',''
UNION ALL SELECT 96,'ZaN_KnSLp','Identyfikator osoby (LP)','','-','techniczne','Nie','Null',''
UNION ALL SELECT 97,'ZaN_KnSTypP','Identyfikator osoby potwierdzajacej (Typ)','','-','techniczne','Nie','Null',''
UNION ALL SELECT 98,'ZaN_KnSFirmaP','Identyfikator osoby potwierdzajacej (Firma)','','-','techniczne','Nie','Null',''
UNION ALL SELECT 99,'ZaN_KnSNumerP','Identyfikator osoby potwierdzajacej (Numer)','','-','techniczne','Nie','Null',''
UNION ALL SELECT 100,'ZaN_KnSLpP','LP osoby odpow. za dok. pomocniczy','','-','techniczne','Nie','Null',''
UNION ALL SELECT 101,'ZaN_Rodzaj','Rodzaj zamowienia: 4=zewnetrzne, 8=wewnetrzne','4, 8','Rodzaj_Zamowienia','CASE: 4=Zewnetrzne, 8=Wewnetrzne ELSE Nieznane+val','Tak','Rozroznia zamowienia wewnetrzne od zewnetrznych',''
UNION ALL SELECT 102,'ZaN_PcKID','ID oddzialu offline POS w ktorym wystawiono zamowienie','3, 5, 0, 1','ID_Oddzialu_POS','CASE WHEN = 0 THEN NULL','Tak','Powiazanie z oddzialem POS — moze byc przydatne dla bota',''
UNION ALL SELECT 103,'ZaN_KnDTyp','Typ GID odbiorcy','32, 0','-','techniczne','Nie','Para z KnDNumer',''
UNION ALL SELECT 104,'ZaN_KnDFirma','ID firmy odbiorcy','0, 1464833','-','techniczne','Nie','Firma techniczna',''
UNION ALL SELECT 105,'ZaN_KnDNumer','GID odbiorcy (kontrahent docelowy)','1755, 277, 0','ID_Odbiorcy','CASE WHEN = 0 THEN NULL + JOIN CDN.KntKarty (Akronim odbiorcy) — 423/12022 inny niz KntNumer','Tak','Odbiorca moze byc inny niz zamawiajacy kontrahent',''
UNION ALL SELECT 106,'ZaN_KnDLp','LP odbiorcy','','-','techniczne','Nie','LP techniczne',''
UNION ALL SELECT 107,'ZaN_FiaskoID','Identyfikator przyczyny fiaska','351, 69, 0','-','niezidentyfikowane — CDN.Slowniki?','Nie','Nieznane — eskalacja jesli potrzebne',''
UNION ALL SELECT 108,'ZaN_RokMiesiac','Rok i miesiac (YYYYMM) — pole computed','202308, 202404','-','pochodna DataWystawienia — redundantne','Nie','Redundantne',''
UNION ALL SELECT 109,'ZaN_PotwOferty','Stan potwierdzenia oferty: 0=niepotwierdzona, 1=potwierdzona, 2=przyjeta, 3=odrzucona, 4=wyslana, 17=wygenerowano zamowienie','','-','0/12022 — null w danych','Nie','Dotyczy tylko ofert — null w danych',''
UNION ALL SELECT 110,'ZaN_DataPotwOferty','Data potwierdzenia oferty','','-','Clarion DATE — null w danych','Nie','Null',''
UNION ALL SELECT 111,'ZaN_OpeTypPotwOfe','Typ GID op. potwierdzajacego oferte','0, 128','-','techniczne','Nie','Para z NumerPotwOfe',''
UNION ALL SELECT 112,'ZaN_OpeFirmaPotwOfe','ID firmy op. potwierdzajacego oferte','1464833, 0','-','techniczne','Nie','Firma techniczna',''
UNION ALL SELECT 113,'ZaN_OpeNumerPotwOfe','ID op. potwierdzajacego oferte','23, 20, 0','-','JOIN OpeKarty — zbedne dla MVP','Nie','Zbedne',''
UNION ALL SELECT 114,'ZaN_OpeLpPotwOfe','LP op. potwierdzajacego oferte','','-','techniczne','Nie','LP techniczne',''
UNION ALL SELECT 115,'ZaN_DataAktywacjiRez','Data aktywacji rezerwacji','81377, 81348','-','Clarion DATE — szczegolowe technikalia','Nie','Zbedne dla naglowka',''
UNION ALL SELECT 116,'ZaN_Url','Uwagi / komentarz do zamowienia — sample: jutro zabiore, fv Ceim, paragon','jutro zabiore, fv Ceim','Uwagi','NULLIF(RTRIM(val), '''') — 37/12022 wypelnione','Tak','Pole uwag handlowych — wartosc dla bota',''
UNION ALL SELECT 117,'ZaN_RabatW','Rabat kwotowy','','-','0/12022 nonzero','Nie','Zawsze 0',''
UNION ALL SELECT 118,'ZaN_FrSID','Identyfikator miejsca w strukturze firmy (wezla)','1, 6, 75, 79','ID_Firmy_Handlowej','bez zmian + JOIN CDN.FrmStruktura (FRS_Nazwa)','Tak','FK do CDN.FrmStruktura — 12022/12022',''
UNION ALL SELECT 119,'ZaN_FlagaNB','Sposob liczenia — N=netto, B=brutto','N','-','ZWERYFIKOWANE: zawsze N — stala','Nie','Stala N',''
UNION ALL SELECT 120,'ZaN_OpeTypMod','Typ GID op. ostatnio modyfikujacego','128','-','techniczne','Nie','Para z OpeNumerMod',''
UNION ALL SELECT 121,'ZaN_OpeFirmaMod','ID firmy op. ostatnio modyfikujacego','1464833','-','techniczne','Nie','Firma techniczna',''
UNION ALL SELECT 122,'ZaN_OpeNumerMod','Operator ostatnio modyfikujacy (ID) — inny niz OpeNumerM?','30, 27, 10','ID_Operatora_Mod','CASE WHEN = 0 THEN NULL — sprawdzic czy rozni sie od OpeNumerM','Tak','Potencjalnie ostatnia modyfikacja — do weryfikacji z OpeNumerM',''
UNION ALL SELECT 123,'ZaN_OpeLpMod','LP operatora modyfikujacego','','-','techniczne','Nie','LP techniczne',''
UNION ALL SELECT 124,'ZaN_OddDokId','Identyfikator dokumentu nadany w oddziale','2264, 2261, 0','ID_Dok_Oddzialu','CASE WHEN = 0 THEN NULL','Nie','Identyfikator oddzialowy — zbedne dla MVP',''
UNION ALL SELECT 125,'ZaN_LastMod','TimeStamp ostatniej modyfikacji','1062328456, 1062335007','Data_Ostatniej_Modyfikacji','Clarion TIMESTAMP: CAST(DATEADD(ss,val,''1990-01-01'') AS DATETIME)','Tak','Data zmiany rekordu',''
UNION ALL SELECT 126,'ZaN_OpiTyp','Typ opiekuna','0, 944','-','techniczne — 944=Pracownik','Nie','Para z OpiNumer',''
UNION ALL SELECT 127,'ZaN_OpiFirma','ID firmy opiekuna','1464833, 0','-','techniczne','Nie','Firma techniczna',''
UNION ALL SELECT 128,'ZaN_OpiNumer','Opiekun — Pracownik (GIDTyp=944)','0, 1, 6','ID_Opiekuna','CASE WHEN = 0 THEN NULL + JOIN CDN.PrcKarty (Prc_GIDTyp=944) — Prc_Imie1+Prc_Nazwisko','Tak','8204/12022 wypelnione — opiekun handlowy',''
UNION ALL SELECT 129,'ZaN_OpiLP','LP opiekuna','','-','techniczne','Nie','LP techniczne',''
UNION ALL SELECT 130,'ZaN_IncotermsSymbol','Incoterms (symbol) — EXW dla 12021/12022','EXW','Incoterms_Symbol','NULLIF(RTRIM(val), '''')','Nie','EXW stala w 99.99% rekordow',''
UNION ALL SELECT 131,'ZaN_IncotermsMiejsce','Incoterms (miejsce dostarczenia/odbioru)','','-','NULLIF','Nie','Null w danych',''
UNION ALL SELECT 132,'ZaN_KrajPrzezWys','Kraj przeznaczenia wysylki','PL, SI','Kraj_Wysylki','NULLIF(RTRIM(val), '''')','Nie','PL dla wiekszosci — mala wartosc',''
UNION ALL SELECT 133,'ZaN_KodRodzajuTransportu','Kod rodzaju transportu','3','-','enum — niezidentyfikowany slownik','Nie','Znaczenie nieznane',''
UNION ALL SELECT 134,'ZaN_KodRodzajuTransakcji','Kod rodzaju transakcji (celny?)','11','-','enum — niezidentyfikowany slownik','Nie','Znaczenie nieznane',''
UNION ALL SELECT 135,'ZaN_Wyslano','Stan eksportu do zewnetrznego pliku (ECOD)','','-','flaga eksportu EDI — 0/12022','Nie','Null w danych',''
UNION ALL SELECT 136,'ZaN_CenaSpr','Numer ceny domyslnej — 0-9 jak w konfiguracji cennikow','1, 6, 4, 2','ID_Cennika','bez zmian — mozliwy JOIN CDN.TwrCenyNag MIN(TCN_Nazwa) GROUP BY TCN_RodzajCeny','Tak','Cennik przypisany do zamowienia',''
UNION ALL SELECT 137,'ZaN_GodzinaWystawienia','Godzina wystawienia dokumentu (centisekundy od polnocy)','5393467, 2894800','Godzina_Wystawienia','CAST(DATEADD(ss,val/100,''19000101'') AS TIME) — 12022/12022 wypelnione','Tak','Godzina wystawienia',''
UNION ALL SELECT 138,'ZaN_GodzinaPotwierdzenia','Godzina potwierdzenia dokumentu (centisekundy)','5004000, 2532100','Godzina_Potwierdzenia','CAST(DATEADD(ss,val/100,''19000101'') AS TIME) — CASE WHEN = 0 THEN NULL','Tak','Para do Data_Potwierdzenia',''
UNION ALL SELECT 139,'ZaN_Promocje','Promocje (bitmask)','','-','bez opisu — null','Nie','Null w danych',''
UNION ALL SELECT 140,'ZaN_RezerwujZasoby','Czy rezerwowac zasoby','','-','null w danych','Nie','Null',''
UNION ALL SELECT 141,'ZaN_PriorytetRez','Priorytet rezerwacji','20','-','jeden distinct — mala wartosc','Nie','Prawie stala',''
UNION ALL SELECT 142,'ZaN_RabatPromocyjnyGlobalny','Rabat promocyjny globalny','','-','null w danych','Nie','Null',''
UNION ALL SELECT 143,'ZaN_KnPTyp','Typ GID platnika','32, 0','-','techniczne','Nie','Para z KnPNumer',''
UNION ALL SELECT 144,'ZaN_KnPNumer','Identyfikator platnika','2430, 1192, 0','ID_Platnika','CASE WHEN = 0 THEN NULL + JOIN CDN.KntKarty (Akronim platnika) — 1525/12022 inny niz KntNumer','Tak','Platnik moze byc inny niz kontrahent',''
UNION ALL SELECT 145,'ZaN_AdPNumer','Identyfikator adresu platnika','0, 2463','','-','Nie','Zbedne dla MVP',''
UNION ALL SELECT 146,'ZaN_MaGDTyp','Typ magazynu docelowego (tylko ZW)','208, 0','-','techniczne','Nie','Para z MagDNumer',''
UNION ALL SELECT 147,'ZaN_MagDNumer','Magazyn docelowy — wazne tylko dla ZW (zamowien wewnetrznych)','10, 1, 13','ID_Magazynu_Docelowego','CASE WHEN = 0 THEN NULL + JOIN CDN.Magazyny — 1069/12022 wypelnione (= ZaN_Rodzaj=8)','Tak','Magazyn docelowy dla zamowien wewnetrznych',''
UNION ALL SELECT 148,'ZaN_KarNumer','Numer rejestru bankowego','6, 4, 0','-','CASE WHEN = 0 THEN NULL — rzadko wypelnione','Nie','Zbedne dla MVP',''
UNION ALL SELECT 149,'ZaN_PrjId','Identyfikator projektu','','-','0/12022 nonzero — zawsze null','Nie','Zawsze 0',''
UNION ALL SELECT 150,'ZaN_KnSTypOdb','Identyfikator osoby u odbiorcy','','-','null','Nie','Null',''
UNION ALL SELECT 151,'ZaN_KnSFirmaOdb','','','-','null','Nie','Null',''
UNION ALL SELECT 152,'ZaN_KnSNumerOdb','','','-','null','Nie','Null',''
UNION ALL SELECT 153,'ZaN_KnSLpOdb','','','-','null','Nie','Null',''
UNION ALL SELECT 154,'ZaN_KnSTypPlt','Identyfikator osoby u platnika','','-','null','Nie','Null',''
UNION ALL SELECT 155,'ZaN_KnSFirmaPlt','','','-','null','Nie','Null',''
UNION ALL SELECT 156,'ZaN_KnSNumerPlt','','','-','null','Nie','Null',''
UNION ALL SELECT 157,'ZaN_KnSLpPlt','','','-','null','Nie','Null',''
UNION ALL SELECT 158,'ZaN_RodzajDatyRealizacji','Czy data realizacji oferty liczona od daty zamowienia','','-','null w danych','Nie','Null',''
UNION ALL SELECT 159,'ZaN_FrMNumer','Identyfikator pieczatki','1','-','techniczne — stala','Nie','Stala techniczna',''
UNION ALL SELECT 160,'ZaN_PromocjePar','Sposob naliczania rabatow (0=z KGO, 1=bez KGO)','0, 3, 1','-','enum szczegolowy','Nie','Szczegoly rabatow — zbedne',''
UNION ALL SELECT 161,'ZaN_RezerwacjeNaNiepotwierdzonym','Czy tworzyc rezerwacje na niez potwierdzonym ZS','0, 1','Rez_Na_Niepotw','CASE: 0=Nie, 1=Tak','Nie','Parametr techniczny dokumentu',''
UNION ALL SELECT 162,'ZaN_StanZapytania','Stan zapytania ofertowego','','-','null','Nie','Null',''
UNION ALL SELECT 163,'ZaN_OpeNumerPotwZapyt','ID op. ktory potwierdzil zapytanie ofertowe','','-','null','Nie','Null',''
UNION ALL SELECT 164,'ZaN_GenerujWieleZam','Nieobslugiwane od 2018.2','','-','nieobslugiwane','Nie','Wycofane',''
UNION ALL SELECT 165,'ZaN_FormatkaCyr','Cyrylica w polach dat','','-','null','Nie','Null',''
UNION ALL SELECT 166,'ZaN_WtrID','ID promocji wartosciowej','','-','null','Nie','Null',''
UNION ALL SELECT 167,'ZaN_WtrProgID','ID progu promocji wartosciowej','','-','null','Nie','Null',''
UNION ALL SELECT 168,'ZaN_DomyslnyDokRealizacja','Typ domyslnego dok. realizacji zamowienia','0, 2001','-','enum — niezidentyfikowany','Nie','Techniczne',''
UNION ALL SELECT 169,'ZaN_DataPromocjiRodzaj','Rodzaj daty dla ceny poczatkowej: 0=wystawienia, 1=realizacji','1','-','enum — szczegoly promocji','Nie','Szczegoly promocji',''
UNION ALL SELECT 170,'ZaN_RezZasTylkoAktywne','Czy sprawdzac date aktywacji rezerwacji','','-','null','Nie','Null',''
UNION ALL SELECT 171,'ZaN_PrzyczynaZW','Przyczyna zwolnienia z VAT','','-','null','Nie','Null',''
UNION ALL SELECT 172,'ZaN_PodstawaZW','Podstawa zwolnienia z VAT','','-','null','Nie','Null',''
UNION ALL SELECT 173,'ZaN_LimitKredytowy','Czy przyznano limit kredytowy: 0=brak, 1=limit dokumentu','','-','null w danych','Nie','Null',''
UNION ALL SELECT 174,'ZaN_LimitKredytowyKwota','Kwota limitu kredytowego','','-','null w danych','Nie','Null',''
UNION ALL SELECT 175,'ZaN_LimitKredytowyWaznyDo','Data waznosci limitu (93890=bezterminowo)','81545, 93890','-','Clarion DATE — do sprawdzenia','Nie','Zbedne dla MVP',''
UNION ALL SELECT 176,'ZaN_LimitKredytowyWaluta','Symbol waluty limitu','EUR, PLN','-','','Nie','Zbedne dla MVP',''
UNION ALL SELECT 177,'ZaN_KontrolujIlosciPrzyGenZam','Czy kontrolowac ilosci przy gen. zamowien z oferty','','-','null','Nie','Null',''
UNION ALL SELECT 178,'ZaN_OplataSpozFlaga','Czy naliczac oplata spozywcza','','-','null','Nie','Null',''
UNION ALL SELECT 179,'ZaN_GUID','GUID zamowienia z POS','00144029...','GUID_POS','NULLIF(val, '''')','Nie','Techniczne POS — zbedne dla bota',''
UNION ALL SELECT 180,'ZaN_OperatorPOS','Operator wystawiajacy w POS (ID)','18, 57, 0','ID_Operatora_POS','CASE WHEN = 0 THEN NULL','Nie','Zbedne — mamy OpeNumerW',''
UNION ALL SELECT 181,'ZaN_OstatniaModyfikacjaPOS','TimeStamp ostatniej modyfikacji w POS','1054555352, 0','-','Clarion TIMESTAMP — czesto 0','Nie','Zbedne dla MVP',''
UNION ALL SELECT 182,'ZaN_ZrodloPochodzeniaESklep','Zrodlo zamowienia z e-Sklep','','-','null','Nie','Null',''
UNION ALL SELECT 183,'ZaN_StatusPlatnosciPOS','Status platnosci POS (CDN.Slowniki)','','-','null','Nie','Null',''
UNION ALL SELECT 184,'ZaN_StatusRealizacji','Status realizacji — powiazanie z CDN.Slowniki','1182, 0, 1179','Status_Realizacji','JOIN CDN.Slowniki: 0=brak, 1182=Anulowane, 1179=Wyslane ELSE Nieznane+val','Tak','Slownik statusow realizacji',''
UNION ALL SELECT 185,'ZaN_EAN','Kod EAN zamowienia z POS','','-','null','Nie','Null',''
UNION ALL SELECT 186,'ZaN_PsAID','ID stanowiska POS ostatnio modyfikujacego','','-','techniczne POS','Nie','Techniczne POS',''
UNION ALL SELECT 187,'[KOLUMNA SYNTETYCZNA] Numer_Dokumentu','Inline construction z ZaN_ZamTyp/Numer/Rok/Mies/Seria','','Numer_Dokumentu','CASE ZaN_ZamTyp: 640=OFZ, 768=OFS, 1152=ZZ, 1280=ZS + ''-''+Numer+''/''+MM+''/''+RRRR+''/''+Seria — przyklad: ZS-2/05/2023/PH_4','Tak','Numer czytelny dla bota — priorytet 1',''
UNION ALL SELECT 188,'[KOLUMNA SYNTETYCZNA] Numer_Potwierdzenia','Inline construction z ZaN_PomTyp/PomNumer/PomRok/PomMies/PomSeria','','Numer_Potwierdzenia','Analogicznie do Numer_Dokumentu — CASE na PomTyp','Tak','Numer dokumentu potwierdzajacego',''
UNION ALL SELECT 189,'[JOIN] CDN.KntKarty (kontrahent)','Knt_Akronim, Knt_Nazwa1','','Akronim_Kontrahenta, Nazwa_Kontrahenta','LEFT JOIN ON Knt_GIDNumer = ZaN_KntNumer AND ZaN_KntNumer > 0','Tak','10742/12022',''
UNION ALL SELECT 190,'[JOIN] CDN.KntAdresy (adres knt)','KnA_Akronim, KnA_Miasto, KnA_KodP, KnA_Ulica, KnA_Adres','','Miasto_Knt, KodP_Knt, Ulica_Knt','LEFT JOIN ON KnA_GIDNumer = ZaN_KnANumer AND ZaN_KnANumer > 0','Tak','Adres korespondencyjny',''
UNION ALL SELECT 191,'[JOIN] CDN.KntAdresy (adres wysylki)','KnA_Akronim, KnA_Miasto, KnA_KodP, KnA_Ulica','','Miasto_Wysylki, KodP_Wysylki, Ulica_Wysylki','LEFT JOIN ON KnA_GIDNumer = ZaN_AdWNumer AND ZaN_AdWNumer > 0','Tak','Adres dostawy',''
UNION ALL SELECT 192,'[JOIN] CDN.Magazyny','MAG_Kod, MAG_Nazwa','','Kod_Magazynu, Nazwa_Magazynu','LEFT JOIN ON MAG_GIDNumer = ZaN_MagNumer AND ZaN_MagNumer > 0','Tak','12021/12022',''
UNION ALL SELECT 193,'[JOIN] CDN.OpeKarty (wystawiajacy)','Ope_Ident','','Operator_Wystawiajacy','LEFT JOIN ON Ope_GIDNumer = ZaN_OpeNumerW AND ZaN_OpeNumerW > 0','Tak','',''
UNION ALL SELECT 194,'[JOIN] CDN.OpeKarty (modyfikujacy)','Ope_Ident','','Operator_Modyfikujacy','LEFT JOIN ON Ope_GIDNumer = ZaN_OpeNumerM AND ZaN_OpeNumerM > 0','Tak','',''
UNION ALL SELECT 195,'[JOIN] CDN.OpeKarty (zatwierdzajacy)','Ope_Ident','','Operator_Zatwierdzajacy','LEFT JOIN ON Ope_GIDNumer = ZaN_OpeNumerZ AND ZaN_OpeNumerZ > 0','Tak','',''
UNION ALL SELECT 196,'[JOIN] CDN.FrmStruktura','FRS_Nazwa','','Firma_Handlowa','LEFT JOIN ON FRS_ID = ZaN_FrSID AND ZaN_FrSID > 0','Tak','12022/12022',''
UNION ALL SELECT 197,'[JOIN] CDN.KntKarty (akwizytor)','Knt_Akronim','','Akwizytor','LEFT JOIN ON Knt_GIDNumer = ZaN_AkwNumer AND ZaN_AkwNumer > 0','Tak','10649/12022',''
UNION ALL SELECT 198,'[JOIN] CDN.KntKarty (odbiorca)','Knt_Akronim, Knt_Nazwa1','','Akronim_Odbiorcy, Nazwa_Odbiorcy','LEFT JOIN ON Knt_GIDNumer = ZaN_KnDNumer AND ZaN_KnDNumer > 0','Tak','423/12022 inny niz kontrahent',''
UNION ALL SELECT 199,'[JOIN] CDN.KntKarty (platnik)','Knt_Akronim, Knt_Nazwa1','','Akronim_Platnika, Nazwa_Platnika','LEFT JOIN ON Knt_GIDNumer = ZaN_KnPNumer AND ZaN_KnPNumer > 0','Tak','1525/12022 inny niz kontrahent',''
UNION ALL SELECT 200,'[JOIN] CDN.PrcKarty (opiekun)','Prc_Akronim, Prc_Imie1+Prc_Nazwisko','','Opiekun','LEFT JOIN ON Prc_GIDNumer = ZaN_OpiNumer AND Prc_GIDTyp = 944 AND ZaN_OpiNumer > 0','Tak','8204/12022',''
UNION ALL SELECT 201,'[JOIN] CDN.Magazyny (docelowy)','MAG_Kod, MAG_Nazwa','','Kod_Magazynu_Doc, Nazwa_Magazynu_Doc','LEFT JOIN ON MAG_GIDNumer = ZaN_MagDNumer AND ZaN_MagDNumer > 0','Tak','1069/12022 — tylko ZW',''
UNION ALL SELECT 202,'[JOIN] CDN.TwrCenyNag (cennik)','MIN(TCN_Nazwa) GROUP BY TCN_RodzajCeny','','Nazwa_Cennika','LEFT JOIN ON TCN_RodzajCeny = ZaN_CenaSpr — subquery MIN','Tak','Cennik zamowienia',''
ORDER BY Kolejnosc
