SELECT 1 AS Kolejnosc, 'TwG_GIDTyp'            AS CDN_Pole, 'Identyfikator grupy lub elementu'         AS Opis_w_dokumentacji, '-16, 16' AS Przykladowe_wartosci,  '-'                 AS Alias_w_widoku,  'Filtr techniczny (GIDTyp=16 bridge)'      AS Transformacja, 'Nie' AS Uwzglednic, 'Stała techniczna — filtr WHERE'         AS Uzasadnienie, '' AS Komentarz_Usera UNION ALL
SELECT 2, 'TwG_GIDFirma',           'Identyfikator grupy lub elementu (firma)', '1464833',               '-',                 'Stała — jedna firma',                     'Nie',  'GIDFirma zawsze pomijamy',              '' UNION ALL
SELECT 3, 'TwG_GIDNumer',           'Identyfikator grupy lub elementu',         '5140, 8482, 7993',      'ID_Towaru',         'Klucz towaru z CDN.TwrKarty',             'Tak',  'PK widoku — JOIN do TwrKarty',          '' UNION ALL
SELECT 4, 'TwG_GIDLp',              'Identyfikator grupy lub elementu',         '0',                     '-',                 'Stała 0',                                 'Nie',  'GIDLp zawsze pomijamy',                 '' UNION ALL
SELECT 5, 'TwG_GrOTyp',             'Identyfikator grupy nadrzędnej',           '-16',                   '-',                 'Stała — typ grupy',                       'Nie',  'Stała techniczna',                      '' UNION ALL
SELECT 6, 'TwG_GrOFirma',          'Identyfikator grupy nadrzędnej (firma)',    '1464833',               '-',                 'Stała — jedna firma',                     'Nie',  'GIDFirma zawsze pomijamy',              '' UNION ALL
SELECT 7, 'TwG_GrONumer',           'Identyfikator grupy nadrzędnej',           '72, 5472, 49',          'ID_Grupy',          'Klucz grupy ogólnej (GIDTyp=-16)',         'Tak',  'FK do definicji grupy',                 '' UNION ALL
SELECT 8, 'TwG_GrOLp',              'Identyfikator grupy nadrzędnej',           '0',                     '-',                 'Stała 0',                                 'Nie',  'GIDLp zawsze pomijamy',                 '' UNION ALL
SELECT 9, 'TwG_Kod',                'Kod grupy lub elementu',                   'CZNI0061, TEST0001',    'Kod_Towaru',        'JOIN CDN.TwrKarty → Twr_Kod (towar)',     'Tak',  'Kod towaru — JOIN preferred over stored','' UNION ALL
SELECT 10,'TwG_Nazwa',              'Nazwa grupy lub elementu',                 'Choinka CH 10',         'Nazwa_Towaru',      'JOIN CDN.TwrKarty → Twr_Nazwa',           'Tak',  'Nazwa towaru — JOIN preferred',          '' UNION ALL
SELECT 11,'TwG_CzasModyfikacji',    'Data i czas ostatniej modyfikacji',        '1054464514',            'Data_Modyfikacji',  'DATEADD(ss, val, 1990-01-01)',             'Tak',  'Clarion TIMESTAMP — kiedy zmieniono przypisanie','  ' UNION ALL
SELECT 12,'TwG_SyncId',             'Identyfikator dla synchronizacji',         '28, 18',                '-',                 'Techniczne sync',                         'Nie',  'Brak wartości BI',                      '' UNION ALL
SELECT 13,'TwG_KategoriaBIId',      'Identyfikator kategorii BI grup towarowych','0',                   '-',                 'Stała 0 dla wszystkich rekordów',         'Nie',  'COUNT DISTINCT = 1 (wartość: 0)',        '' UNION ALL
SELECT 14,'[JOIN] Twr_Kod',         '',                                          '',                     'Kod_Towaru',        'CDN.TwrKarty.Twr_Kod',                    'Tak',  'Kod towaru ze źródła',                  '' UNION ALL
SELECT 15,'[JOIN] Twr_Nazwa',       '',                                          '',                     'Nazwa_Towaru',      'CDN.TwrKarty.Twr_Nazwa',                  'Tak',  'Nazwa towaru ze źródła',                '' UNION ALL
SELECT 16,'[JOIN grp] TwG_Kod',     '',                                          '',                     'Kod_Grupy',         'CDN.TwrGrupy(GIDTyp=-16).TwG_Kod',        'Tak',  'Kod grupy ogólnej',                     '' UNION ALL
SELECT 17,'[JOIN grp] TwG_Nazwa',   '',                                          '',                     'Nazwa_Grupy',       'CDN.TwrGrupy(GIDTyp=-16).TwG_Nazwa',      'Tak',  'Nazwa grupy ogólnej',                   ''
