SELECT 1 AS Kolejnosc, 'KnG_GIDTyp'            AS CDN_Pole, 'Identyfikator grupy lub elementu'              AS Opis_w_dokumentacji, '32, -32' AS Przykladowe_wartosci, '-'                  AS Alias_w_widoku,  'Filtr techniczny (GIDTyp=32 bridge)'      AS Transformacja, 'Nie' AS Uwzglednic, 'Stała techniczna — filtr WHERE'          AS Uzasadnienie, '' AS Komentarz_Usera UNION ALL
SELECT 2, 'KnG_GIDFirma',           'Identyfikator grupy lub elementu (firma)',     '1464833',              '-',                  'Stała — jedna firma',                     'Nie',  'GIDFirma zawsze pomijamy',               '' UNION ALL
SELECT 3, 'KnG_GIDNumer',           'Identyfikator grupy lub elementu',             '1675, 155, 302',       'ID_Kontrahenta',     'Klucz kontrahenta z CDN.KntKarty',        'Tak',  'PK widoku — JOIN do KntKarty',           '' UNION ALL
SELECT 4, 'KnG_GIDLp',              'Identyfikator grupy lub elementu',             '0',                    '-',                  'Stała 0',                                 'Nie',  'GIDLp zawsze pomijamy',                  '' UNION ALL
SELECT 5, 'KnG_GrOTyp',             'Identyfikator grupy nadrzędnej (typ)',         '-32',                  '-',                  'Stała — typ grupy',                       'Nie',  'Stała techniczna',                       '' UNION ALL
SELECT 6, 'KnG_GrOFirma',           'Identyfikator grupy nadrzędnej (firma)',       '1464833',              '-',                  'Stała — jedna firma',                     'Nie',  'GIDFirma zawsze pomijamy',               '' UNION ALL
SELECT 7, 'KnG_GrONumer',           'Identyfikator grupy nadrzędnej',               '3, 0, 9, 14',          'ID_Grupy',           'Klucz grupy ogólnej (GIDTyp=-32)',         'Tak',  'FK do definicji grupy',                  '' UNION ALL
SELECT 8, 'KnG_GrOLp',              'Identyfikator grupy nadrzędnej',               '0',                    '-',                  'Stała 0',                                 'Nie',  'GIDLp zawsze pomijamy',                  '' UNION ALL
SELECT 9, 'KnG_Akronim',            'Skrócona nazwa grupy lub elementu',            'JEDNORAZOWY, KS_SZKŁO','Akronim_Kontrahenta','JOIN CDN.KntKarty → Knt_Akronim',         'Tak',  'Akronim kontrahenta — JOIN preferred',   '' UNION ALL
SELECT 10,'KnG_CzasModyfikacji',    'Time Stamp modyfikacji Grupy',                 '1047753496',           'Data_Modyfikacji',   'DATEADD(ss, val, 1990-01-01)',             'Tak',  'Clarion TIMESTAMP — kiedy zmieniono przypisanie','  ' UNION ALL
SELECT 11,'KnG_OpeNumer',           'Numer operatora, który założył grupę',         '29, 49, 20',           '-',                  'Techniczne — klucz operatora',            'Nie',  'Brak join OpeKarty w bridge (niska wartość BI)','  ' UNION ALL
SELECT 12,'KnG_CzasZalozenia',      'Time Stamp założenia Grupy',                   '0, 1043530052',        'Data_Zalozenia',     'DATEADD(ss, val, 1990-01-01); NULL gdy 0', 'Tak', 'Kiedy dodano kontrahenta do grupy',      '' UNION ALL
SELECT 13,'KnG_SyncId',             'Identyfikator dla synchronizacji',             '7, 9, 8',              '-',                  'Techniczne sync',                         'Nie',  'Brak wartości BI',                       '' UNION ALL
SELECT 14,'[JOIN] Knt_Akronim',     '',                                              '',                    'Akronim_Kontrahenta','CDN.KntKarty.Knt_Akronim',                'Tak',  'Akronim kontrahenta ze źródła',           '' UNION ALL
SELECT 15,'[JOIN] Knt_Nazwa1',      '',                                              '',                    'Nazwa_Kontrahenta',  'CDN.KntKarty.Knt_Nazwa1',                 'Tak',  'Nazwa kontrahenta',                      '' UNION ALL
SELECT 16,'[JOIN grp] KnG_Akronim', '',                                              '',                    'Kod_Grupy',          'CDN.KntGrupy(GIDTyp=-32).KnG_Akronim',    'Tak',  'Kod grupy ogólnej',                      ''
